/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Add: typeof import('./src/components/icons/Add.vue')['default']
    Bell: typeof import('./src/components/icons/Bell.vue')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    CheckIcon: typeof import('./src/components/icons/CheckIcon.vue')['default']
    Credit: typeof import('./src/components/icons/Credit.vue')['default']
    DashboardLayout: typeof import('./src/components/DashboardLayout.vue')['default']
    Home: typeof import('./src/components/icons/Home.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Layout: typeof import('./src/components/icons/Layout.vue')['default']
    Message: typeof import('primevue/message')['default']
    Password: typeof import('primevue/password')['default']
    RootLayout: typeof import('./src/components/RootLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestIcon: typeof import('./src/components/icons/TestIcon.vue')['default']
    Upload: typeof import('./src/components/icons/Upload.vue')['default']
    Video: typeof import('./src/components/icons/Video.vue')['default']
    VueHead: typeof import('./src/components/VueHead.tsx')['default']
  }
}

// For TSX support
declare global {
  const Add: typeof import('./src/components/icons/Add.vue')['default']
  const Bell: typeof import('./src/components/icons/Bell.vue')['default']
  const Button: typeof import('primevue/button')['default']
  const Checkbox: typeof import('primevue/checkbox')['default']
  const CheckIcon: typeof import('./src/components/icons/CheckIcon.vue')['default']
  const Credit: typeof import('./src/components/icons/Credit.vue')['default']
  const DashboardLayout: typeof import('./src/components/DashboardLayout.vue')['default']
  const Home: typeof import('./src/components/icons/Home.vue')['default']
  const InputText: typeof import('primevue/inputtext')['default']
  const Layout: typeof import('./src/components/icons/Layout.vue')['default']
  const Message: typeof import('primevue/message')['default']
  const Password: typeof import('primevue/password')['default']
  const RootLayout: typeof import('./src/components/RootLayout.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TestIcon: typeof import('./src/components/icons/TestIcon.vue')['default']
  const Upload: typeof import('./src/components/icons/Upload.vue')['default']
  const Video: typeof import('./src/components/icons/Video.vue')['default']
  const VueHead: typeof import('./src/components/VueHead.tsx')['default']
}