// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: agent/v1/woodpecker.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientReadableStream,
  type ClientUnaryCall,
  type ClientWritableStream,
  type handleClientStreamingCall,
  type handleServerStreamingCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export const protobufPackage = "proto";

export interface StepState {
  stepUuid?: string | undefined;
  started?: number | undefined;
  finished?: number | undefined;
  exited?: boolean | undefined;
  exitCode?: number | undefined;
  error?: string | undefined;
  canceled?: boolean | undefined;
}

export interface WorkflowState {
  started?: number | undefined;
  finished?: number | undefined;
  error?: string | undefined;
  canceled?: boolean | undefined;
}

export interface LogEntry {
  stepUuid?: string | undefined;
  time?: number | undefined;
  line?:
    | number
    | undefined;
  /** 0 = stdout, 1 = stderr, 2 = exit-code, 3 = metadata, 4 = progress */
  type?: number | undefined;
  data?: Buffer | undefined;
}

export interface Filter {
  labels?: { [key: string]: string } | undefined;
}

export interface Filter_LabelsEntry {
  key: string;
  value: string;
}

export interface Workflow {
  id?: string | undefined;
  timeout?: number | undefined;
  payload?: Buffer | undefined;
  cancel?: boolean | undefined;
}

export interface NextRequest {
  filter?: Filter | undefined;
}

export interface InitRequest {
  id?: string | undefined;
  state?: WorkflowState | undefined;
}

export interface WaitRequest {
  id?: string | undefined;
}

export interface DoneRequest {
  id?: string | undefined;
  state?: WorkflowState | undefined;
}

export interface ExtendRequest {
  id?: string | undefined;
}

export interface UpdateRequest {
  id?: string | undefined;
  state?: StepState | undefined;
}

export interface LogRequest {
  logEntries?: LogEntry[] | undefined;
}

export interface Empty {
}

export interface ReportHealthRequest {
  status?: string | undefined;
}

export interface AgentInfo {
  platform?: string | undefined;
  capacity?: number | undefined;
  backend?: string | undefined;
  version?: string | undefined;
  customLabels?: { [key: string]: string } | undefined;
}

export interface AgentInfo_CustomLabelsEntry {
  key: string;
  value: string;
}

export interface RegisterAgentRequest {
  info?: AgentInfo | undefined;
}

export interface VersionResponse {
  grpcVersion?: number | undefined;
  serverVersion?: string | undefined;
}

export interface NextResponse {
  workflow?: Workflow | undefined;
}

export interface RegisterAgentResponse {
  agentId?: string | undefined;
}

export interface WaitResponse {
  canceled?: boolean | undefined;
}

export interface AuthRequest {
  agentToken?: string | undefined;
  agentId?: string | undefined;
  hostname?: string | undefined;
}

export interface AuthResponse {
  status?: string | undefined;
  agentId?: string | undefined;
  accessToken?: string | undefined;
}

export interface StreamOptions {
  filter?: Filter | undefined;
}

export interface StatusUpdate {
  stepUuid?: string | undefined;
  time?:
    | number
    | undefined;
  /** 0=stdout, 1=stderr, 2=exit-code, 3=metadata, 4=progress, 5=system-resource */
  type?: number | undefined;
  data?: Buffer | undefined;
}

function createBaseStepState(): StepState {
  return { stepUuid: "", started: 0, finished: 0, exited: false, exitCode: 0, error: "", canceled: false };
}

export const StepState: MessageFns<StepState> = {
  encode(message: StepState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stepUuid !== undefined && message.stepUuid !== "") {
      writer.uint32(10).string(message.stepUuid);
    }
    if (message.started !== undefined && message.started !== 0) {
      writer.uint32(16).int64(message.started);
    }
    if (message.finished !== undefined && message.finished !== 0) {
      writer.uint32(24).int64(message.finished);
    }
    if (message.exited !== undefined && message.exited !== false) {
      writer.uint32(32).bool(message.exited);
    }
    if (message.exitCode !== undefined && message.exitCode !== 0) {
      writer.uint32(40).int32(message.exitCode);
    }
    if (message.error !== undefined && message.error !== "") {
      writer.uint32(50).string(message.error);
    }
    if (message.canceled !== undefined && message.canceled !== false) {
      writer.uint32(56).bool(message.canceled);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StepState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStepState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.stepUuid = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.started = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.finished = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.exited = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.exitCode = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.canceled = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StepState {
    return {
      stepUuid: isSet(object.stepUuid)
        ? globalThis.String(object.stepUuid)
        : isSet(object.step_uuid)
        ? globalThis.String(object.step_uuid)
        : "",
      started: isSet(object.started) ? globalThis.Number(object.started) : 0,
      finished: isSet(object.finished) ? globalThis.Number(object.finished) : 0,
      exited: isSet(object.exited) ? globalThis.Boolean(object.exited) : false,
      exitCode: isSet(object.exitCode)
        ? globalThis.Number(object.exitCode)
        : isSet(object.exit_code)
        ? globalThis.Number(object.exit_code)
        : 0,
      error: isSet(object.error) ? globalThis.String(object.error) : "",
      canceled: isSet(object.canceled) ? globalThis.Boolean(object.canceled) : false,
    };
  },

  toJSON(message: StepState): unknown {
    const obj: any = {};
    if (message.stepUuid !== undefined && message.stepUuid !== "") {
      obj.stepUuid = message.stepUuid;
    }
    if (message.started !== undefined && message.started !== 0) {
      obj.started = Math.round(message.started);
    }
    if (message.finished !== undefined && message.finished !== 0) {
      obj.finished = Math.round(message.finished);
    }
    if (message.exited !== undefined && message.exited !== false) {
      obj.exited = message.exited;
    }
    if (message.exitCode !== undefined && message.exitCode !== 0) {
      obj.exitCode = Math.round(message.exitCode);
    }
    if (message.error !== undefined && message.error !== "") {
      obj.error = message.error;
    }
    if (message.canceled !== undefined && message.canceled !== false) {
      obj.canceled = message.canceled;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StepState>, I>>(base?: I): StepState {
    return StepState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StepState>, I>>(object: I): StepState {
    const message = createBaseStepState();
    message.stepUuid = object.stepUuid ?? "";
    message.started = object.started ?? 0;
    message.finished = object.finished ?? 0;
    message.exited = object.exited ?? false;
    message.exitCode = object.exitCode ?? 0;
    message.error = object.error ?? "";
    message.canceled = object.canceled ?? false;
    return message;
  },
};

function createBaseWorkflowState(): WorkflowState {
  return { started: 0, finished: 0, error: "", canceled: false };
}

export const WorkflowState: MessageFns<WorkflowState> = {
  encode(message: WorkflowState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.started !== undefined && message.started !== 0) {
      writer.uint32(8).int64(message.started);
    }
    if (message.finished !== undefined && message.finished !== 0) {
      writer.uint32(16).int64(message.finished);
    }
    if (message.error !== undefined && message.error !== "") {
      writer.uint32(26).string(message.error);
    }
    if (message.canceled !== undefined && message.canceled !== false) {
      writer.uint32(32).bool(message.canceled);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WorkflowState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWorkflowState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.started = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.finished = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.canceled = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WorkflowState {
    return {
      started: isSet(object.started) ? globalThis.Number(object.started) : 0,
      finished: isSet(object.finished) ? globalThis.Number(object.finished) : 0,
      error: isSet(object.error) ? globalThis.String(object.error) : "",
      canceled: isSet(object.canceled) ? globalThis.Boolean(object.canceled) : false,
    };
  },

  toJSON(message: WorkflowState): unknown {
    const obj: any = {};
    if (message.started !== undefined && message.started !== 0) {
      obj.started = Math.round(message.started);
    }
    if (message.finished !== undefined && message.finished !== 0) {
      obj.finished = Math.round(message.finished);
    }
    if (message.error !== undefined && message.error !== "") {
      obj.error = message.error;
    }
    if (message.canceled !== undefined && message.canceled !== false) {
      obj.canceled = message.canceled;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WorkflowState>, I>>(base?: I): WorkflowState {
    return WorkflowState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WorkflowState>, I>>(object: I): WorkflowState {
    const message = createBaseWorkflowState();
    message.started = object.started ?? 0;
    message.finished = object.finished ?? 0;
    message.error = object.error ?? "";
    message.canceled = object.canceled ?? false;
    return message;
  },
};

function createBaseLogEntry(): LogEntry {
  return { stepUuid: "", time: 0, line: 0, type: 0, data: Buffer.alloc(0) };
}

export const LogEntry: MessageFns<LogEntry> = {
  encode(message: LogEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stepUuid !== undefined && message.stepUuid !== "") {
      writer.uint32(10).string(message.stepUuid);
    }
    if (message.time !== undefined && message.time !== 0) {
      writer.uint32(16).int64(message.time);
    }
    if (message.line !== undefined && message.line !== 0) {
      writer.uint32(24).int32(message.line);
    }
    if (message.type !== undefined && message.type !== 0) {
      writer.uint32(32).int32(message.type);
    }
    if (message.data !== undefined && message.data.length !== 0) {
      writer.uint32(42).bytes(message.data);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.stepUuid = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.time = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.line = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.type = reader.int32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.data = Buffer.from(reader.bytes());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogEntry {
    return {
      stepUuid: isSet(object.stepUuid)
        ? globalThis.String(object.stepUuid)
        : isSet(object.step_uuid)
        ? globalThis.String(object.step_uuid)
        : "",
      time: isSet(object.time) ? globalThis.Number(object.time) : 0,
      line: isSet(object.line) ? globalThis.Number(object.line) : 0,
      type: isSet(object.type) ? globalThis.Number(object.type) : 0,
      data: isSet(object.data) ? Buffer.from(bytesFromBase64(object.data)) : Buffer.alloc(0),
    };
  },

  toJSON(message: LogEntry): unknown {
    const obj: any = {};
    if (message.stepUuid !== undefined && message.stepUuid !== "") {
      obj.stepUuid = message.stepUuid;
    }
    if (message.time !== undefined && message.time !== 0) {
      obj.time = Math.round(message.time);
    }
    if (message.line !== undefined && message.line !== 0) {
      obj.line = Math.round(message.line);
    }
    if (message.type !== undefined && message.type !== 0) {
      obj.type = Math.round(message.type);
    }
    if (message.data !== undefined && message.data.length !== 0) {
      obj.data = base64FromBytes(message.data);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogEntry>, I>>(base?: I): LogEntry {
    return LogEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogEntry>, I>>(object: I): LogEntry {
    const message = createBaseLogEntry();
    message.stepUuid = object.stepUuid ?? "";
    message.time = object.time ?? 0;
    message.line = object.line ?? 0;
    message.type = object.type ?? 0;
    message.data = object.data ?? Buffer.alloc(0);
    return message;
  },
};

function createBaseFilter(): Filter {
  return { labels: {} };
}

export const Filter: MessageFns<Filter> = {
  encode(message: Filter, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    globalThis.Object.entries(message.labels || {}).forEach(([key, value]: [string, string]) => {
      Filter_LabelsEntry.encode({ key: key as any, value }, writer.uint32(10).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Filter {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFilter();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          const entry1 = Filter_LabelsEntry.decode(reader, reader.uint32());
          if (entry1.value !== undefined) {
            message.labels![entry1.key] = entry1.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Filter {
    return {
      labels: isObject(object.labels)
        ? (globalThis.Object.entries(object.labels) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: Filter): unknown {
    const obj: any = {};
    if (message.labels) {
      const entries = globalThis.Object.entries(message.labels) as [string, string][];
      if (entries.length > 0) {
        obj.labels = {};
        entries.forEach(([k, v]) => {
          obj.labels[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Filter>, I>>(base?: I): Filter {
    return Filter.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Filter>, I>>(object: I): Filter {
    const message = createBaseFilter();
    message.labels = (globalThis.Object.entries(object.labels ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseFilter_LabelsEntry(): Filter_LabelsEntry {
  return { key: "", value: "" };
}

export const Filter_LabelsEntry: MessageFns<Filter_LabelsEntry> = {
  encode(message: Filter_LabelsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Filter_LabelsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFilter_LabelsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Filter_LabelsEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: Filter_LabelsEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Filter_LabelsEntry>, I>>(base?: I): Filter_LabelsEntry {
    return Filter_LabelsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Filter_LabelsEntry>, I>>(object: I): Filter_LabelsEntry {
    const message = createBaseFilter_LabelsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseWorkflow(): Workflow {
  return { id: "", timeout: 0, payload: Buffer.alloc(0), cancel: false };
}

export const Workflow: MessageFns<Workflow> = {
  encode(message: Workflow, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined && message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.timeout !== undefined && message.timeout !== 0) {
      writer.uint32(16).int64(message.timeout);
    }
    if (message.payload !== undefined && message.payload.length !== 0) {
      writer.uint32(26).bytes(message.payload);
    }
    if (message.cancel !== undefined && message.cancel !== false) {
      writer.uint32(32).bool(message.cancel);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Workflow {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWorkflow();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.timeout = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.payload = Buffer.from(reader.bytes());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.cancel = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Workflow {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      timeout: isSet(object.timeout) ? globalThis.Number(object.timeout) : 0,
      payload: isSet(object.payload) ? Buffer.from(bytesFromBase64(object.payload)) : Buffer.alloc(0),
      cancel: isSet(object.cancel) ? globalThis.Boolean(object.cancel) : false,
    };
  },

  toJSON(message: Workflow): unknown {
    const obj: any = {};
    if (message.id !== undefined && message.id !== "") {
      obj.id = message.id;
    }
    if (message.timeout !== undefined && message.timeout !== 0) {
      obj.timeout = Math.round(message.timeout);
    }
    if (message.payload !== undefined && message.payload.length !== 0) {
      obj.payload = base64FromBytes(message.payload);
    }
    if (message.cancel !== undefined && message.cancel !== false) {
      obj.cancel = message.cancel;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Workflow>, I>>(base?: I): Workflow {
    return Workflow.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Workflow>, I>>(object: I): Workflow {
    const message = createBaseWorkflow();
    message.id = object.id ?? "";
    message.timeout = object.timeout ?? 0;
    message.payload = object.payload ?? Buffer.alloc(0);
    message.cancel = object.cancel ?? false;
    return message;
  },
};

function createBaseNextRequest(): NextRequest {
  return { filter: undefined };
}

export const NextRequest: MessageFns<NextRequest> = {
  encode(message: NextRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.filter !== undefined) {
      Filter.encode(message.filter, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NextRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNextRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.filter = Filter.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NextRequest {
    return { filter: isSet(object.filter) ? Filter.fromJSON(object.filter) : undefined };
  },

  toJSON(message: NextRequest): unknown {
    const obj: any = {};
    if (message.filter !== undefined) {
      obj.filter = Filter.toJSON(message.filter);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NextRequest>, I>>(base?: I): NextRequest {
    return NextRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NextRequest>, I>>(object: I): NextRequest {
    const message = createBaseNextRequest();
    message.filter = (object.filter !== undefined && object.filter !== null)
      ? Filter.fromPartial(object.filter)
      : undefined;
    return message;
  },
};

function createBaseInitRequest(): InitRequest {
  return { id: "", state: undefined };
}

export const InitRequest: MessageFns<InitRequest> = {
  encode(message: InitRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined && message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.state !== undefined) {
      WorkflowState.encode(message.state, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InitRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInitRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.state = WorkflowState.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InitRequest {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      state: isSet(object.state) ? WorkflowState.fromJSON(object.state) : undefined,
    };
  },

  toJSON(message: InitRequest): unknown {
    const obj: any = {};
    if (message.id !== undefined && message.id !== "") {
      obj.id = message.id;
    }
    if (message.state !== undefined) {
      obj.state = WorkflowState.toJSON(message.state);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InitRequest>, I>>(base?: I): InitRequest {
    return InitRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InitRequest>, I>>(object: I): InitRequest {
    const message = createBaseInitRequest();
    message.id = object.id ?? "";
    message.state = (object.state !== undefined && object.state !== null)
      ? WorkflowState.fromPartial(object.state)
      : undefined;
    return message;
  },
};

function createBaseWaitRequest(): WaitRequest {
  return { id: "" };
}

export const WaitRequest: MessageFns<WaitRequest> = {
  encode(message: WaitRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined && message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WaitRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWaitRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WaitRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: WaitRequest): unknown {
    const obj: any = {};
    if (message.id !== undefined && message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WaitRequest>, I>>(base?: I): WaitRequest {
    return WaitRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WaitRequest>, I>>(object: I): WaitRequest {
    const message = createBaseWaitRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseDoneRequest(): DoneRequest {
  return { id: "", state: undefined };
}

export const DoneRequest: MessageFns<DoneRequest> = {
  encode(message: DoneRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined && message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.state !== undefined) {
      WorkflowState.encode(message.state, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DoneRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDoneRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.state = WorkflowState.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DoneRequest {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      state: isSet(object.state) ? WorkflowState.fromJSON(object.state) : undefined,
    };
  },

  toJSON(message: DoneRequest): unknown {
    const obj: any = {};
    if (message.id !== undefined && message.id !== "") {
      obj.id = message.id;
    }
    if (message.state !== undefined) {
      obj.state = WorkflowState.toJSON(message.state);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DoneRequest>, I>>(base?: I): DoneRequest {
    return DoneRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DoneRequest>, I>>(object: I): DoneRequest {
    const message = createBaseDoneRequest();
    message.id = object.id ?? "";
    message.state = (object.state !== undefined && object.state !== null)
      ? WorkflowState.fromPartial(object.state)
      : undefined;
    return message;
  },
};

function createBaseExtendRequest(): ExtendRequest {
  return { id: "" };
}

export const ExtendRequest: MessageFns<ExtendRequest> = {
  encode(message: ExtendRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined && message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ExtendRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseExtendRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ExtendRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: ExtendRequest): unknown {
    const obj: any = {};
    if (message.id !== undefined && message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ExtendRequest>, I>>(base?: I): ExtendRequest {
    return ExtendRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ExtendRequest>, I>>(object: I): ExtendRequest {
    const message = createBaseExtendRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseUpdateRequest(): UpdateRequest {
  return { id: "", state: undefined };
}

export const UpdateRequest: MessageFns<UpdateRequest> = {
  encode(message: UpdateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined && message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.state !== undefined) {
      StepState.encode(message.state, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.state = StepState.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateRequest {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      state: isSet(object.state) ? StepState.fromJSON(object.state) : undefined,
    };
  },

  toJSON(message: UpdateRequest): unknown {
    const obj: any = {};
    if (message.id !== undefined && message.id !== "") {
      obj.id = message.id;
    }
    if (message.state !== undefined) {
      obj.state = StepState.toJSON(message.state);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateRequest>, I>>(base?: I): UpdateRequest {
    return UpdateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateRequest>, I>>(object: I): UpdateRequest {
    const message = createBaseUpdateRequest();
    message.id = object.id ?? "";
    message.state = (object.state !== undefined && object.state !== null)
      ? StepState.fromPartial(object.state)
      : undefined;
    return message;
  },
};

function createBaseLogRequest(): LogRequest {
  return { logEntries: [] };
}

export const LogRequest: MessageFns<LogRequest> = {
  encode(message: LogRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.logEntries !== undefined && message.logEntries.length !== 0) {
      for (const v of message.logEntries) {
        LogEntry.encode(v!, writer.uint32(10).fork()).join();
      }
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          const el = LogEntry.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.logEntries!.push(el);
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogRequest {
    return {
      logEntries: globalThis.Array.isArray(object?.logEntries)
        ? object.logEntries.map((e: any) => LogEntry.fromJSON(e))
        : [],
    };
  },

  toJSON(message: LogRequest): unknown {
    const obj: any = {};
    if (message.logEntries?.length) {
      obj.logEntries = message.logEntries.map((e) => LogEntry.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<LogRequest>, I>>(base?: I): LogRequest {
    return LogRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<LogRequest>, I>>(object: I): LogRequest {
    const message = createBaseLogRequest();
    message.logEntries = object.logEntries?.map((e) => LogEntry.fromPartial(e)) || [];
    return message;
  },
};

function createBaseEmpty(): Empty {
  return {};
}

export const Empty: MessageFns<Empty> = {
  encode(_: Empty, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Empty {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmpty();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): Empty {
    return {};
  },

  toJSON(_: Empty): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<Empty>, I>>(base?: I): Empty {
    return Empty.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Empty>, I>>(_: I): Empty {
    const message = createBaseEmpty();
    return message;
  },
};

function createBaseReportHealthRequest(): ReportHealthRequest {
  return { status: "" };
}

export const ReportHealthRequest: MessageFns<ReportHealthRequest> = {
  encode(message: ReportHealthRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== undefined && message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ReportHealthRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseReportHealthRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ReportHealthRequest {
    return { status: isSet(object.status) ? globalThis.String(object.status) : "" };
  },

  toJSON(message: ReportHealthRequest): unknown {
    const obj: any = {};
    if (message.status !== undefined && message.status !== "") {
      obj.status = message.status;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ReportHealthRequest>, I>>(base?: I): ReportHealthRequest {
    return ReportHealthRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ReportHealthRequest>, I>>(object: I): ReportHealthRequest {
    const message = createBaseReportHealthRequest();
    message.status = object.status ?? "";
    return message;
  },
};

function createBaseAgentInfo(): AgentInfo {
  return { platform: "", capacity: 0, backend: "", version: "", customLabels: {} };
}

export const AgentInfo: MessageFns<AgentInfo> = {
  encode(message: AgentInfo, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.platform !== undefined && message.platform !== "") {
      writer.uint32(10).string(message.platform);
    }
    if (message.capacity !== undefined && message.capacity !== 0) {
      writer.uint32(16).int32(message.capacity);
    }
    if (message.backend !== undefined && message.backend !== "") {
      writer.uint32(26).string(message.backend);
    }
    if (message.version !== undefined && message.version !== "") {
      writer.uint32(34).string(message.version);
    }
    globalThis.Object.entries(message.customLabels || {}).forEach(([key, value]: [string, string]) => {
      AgentInfo_CustomLabelsEntry.encode({ key: key as any, value }, writer.uint32(42).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AgentInfo {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAgentInfo();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.platform = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.capacity = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.backend = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.version = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          const entry5 = AgentInfo_CustomLabelsEntry.decode(reader, reader.uint32());
          if (entry5.value !== undefined) {
            message.customLabels![entry5.key] = entry5.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AgentInfo {
    return {
      platform: isSet(object.platform) ? globalThis.String(object.platform) : "",
      capacity: isSet(object.capacity) ? globalThis.Number(object.capacity) : 0,
      backend: isSet(object.backend) ? globalThis.String(object.backend) : "",
      version: isSet(object.version) ? globalThis.String(object.version) : "",
      customLabels: isObject(object.customLabels)
        ? (globalThis.Object.entries(object.customLabels) as [string, any][]).reduce(
          (acc: { [key: string]: string }, [key, value]: [string, any]) => {
            acc[key] = globalThis.String(value);
            return acc;
          },
          {},
        )
        : {},
    };
  },

  toJSON(message: AgentInfo): unknown {
    const obj: any = {};
    if (message.platform !== undefined && message.platform !== "") {
      obj.platform = message.platform;
    }
    if (message.capacity !== undefined && message.capacity !== 0) {
      obj.capacity = Math.round(message.capacity);
    }
    if (message.backend !== undefined && message.backend !== "") {
      obj.backend = message.backend;
    }
    if (message.version !== undefined && message.version !== "") {
      obj.version = message.version;
    }
    if (message.customLabels) {
      const entries = globalThis.Object.entries(message.customLabels) as [string, string][];
      if (entries.length > 0) {
        obj.customLabels = {};
        entries.forEach(([k, v]) => {
          obj.customLabels[k] = v;
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AgentInfo>, I>>(base?: I): AgentInfo {
    return AgentInfo.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AgentInfo>, I>>(object: I): AgentInfo {
    const message = createBaseAgentInfo();
    message.platform = object.platform ?? "";
    message.capacity = object.capacity ?? 0;
    message.backend = object.backend ?? "";
    message.version = object.version ?? "";
    message.customLabels = (globalThis.Object.entries(object.customLabels ?? {}) as [string, string][]).reduce(
      (acc: { [key: string]: string }, [key, value]: [string, string]) => {
        if (value !== undefined) {
          acc[key] = globalThis.String(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseAgentInfo_CustomLabelsEntry(): AgentInfo_CustomLabelsEntry {
  return { key: "", value: "" };
}

export const AgentInfo_CustomLabelsEntry: MessageFns<AgentInfo_CustomLabelsEntry> = {
  encode(message: AgentInfo_CustomLabelsEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AgentInfo_CustomLabelsEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAgentInfo_CustomLabelsEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AgentInfo_CustomLabelsEntry {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: AgentInfo_CustomLabelsEntry): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AgentInfo_CustomLabelsEntry>, I>>(base?: I): AgentInfo_CustomLabelsEntry {
    return AgentInfo_CustomLabelsEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AgentInfo_CustomLabelsEntry>, I>>(object: I): AgentInfo_CustomLabelsEntry {
    const message = createBaseAgentInfo_CustomLabelsEntry();
    message.key = object.key ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseRegisterAgentRequest(): RegisterAgentRequest {
  return { info: undefined };
}

export const RegisterAgentRequest: MessageFns<RegisterAgentRequest> = {
  encode(message: RegisterAgentRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.info !== undefined) {
      AgentInfo.encode(message.info, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegisterAgentRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegisterAgentRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.info = AgentInfo.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RegisterAgentRequest {
    return { info: isSet(object.info) ? AgentInfo.fromJSON(object.info) : undefined };
  },

  toJSON(message: RegisterAgentRequest): unknown {
    const obj: any = {};
    if (message.info !== undefined) {
      obj.info = AgentInfo.toJSON(message.info);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RegisterAgentRequest>, I>>(base?: I): RegisterAgentRequest {
    return RegisterAgentRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RegisterAgentRequest>, I>>(object: I): RegisterAgentRequest {
    const message = createBaseRegisterAgentRequest();
    message.info = (object.info !== undefined && object.info !== null) ? AgentInfo.fromPartial(object.info) : undefined;
    return message;
  },
};

function createBaseVersionResponse(): VersionResponse {
  return { grpcVersion: 0, serverVersion: "" };
}

export const VersionResponse: MessageFns<VersionResponse> = {
  encode(message: VersionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.grpcVersion !== undefined && message.grpcVersion !== 0) {
      writer.uint32(8).int32(message.grpcVersion);
    }
    if (message.serverVersion !== undefined && message.serverVersion !== "") {
      writer.uint32(18).string(message.serverVersion);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): VersionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseVersionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.grpcVersion = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.serverVersion = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): VersionResponse {
    return {
      grpcVersion: isSet(object.grpcVersion)
        ? globalThis.Number(object.grpcVersion)
        : isSet(object.grpc_version)
        ? globalThis.Number(object.grpc_version)
        : 0,
      serverVersion: isSet(object.serverVersion)
        ? globalThis.String(object.serverVersion)
        : isSet(object.server_version)
        ? globalThis.String(object.server_version)
        : "",
    };
  },

  toJSON(message: VersionResponse): unknown {
    const obj: any = {};
    if (message.grpcVersion !== undefined && message.grpcVersion !== 0) {
      obj.grpcVersion = Math.round(message.grpcVersion);
    }
    if (message.serverVersion !== undefined && message.serverVersion !== "") {
      obj.serverVersion = message.serverVersion;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<VersionResponse>, I>>(base?: I): VersionResponse {
    return VersionResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<VersionResponse>, I>>(object: I): VersionResponse {
    const message = createBaseVersionResponse();
    message.grpcVersion = object.grpcVersion ?? 0;
    message.serverVersion = object.serverVersion ?? "";
    return message;
  },
};

function createBaseNextResponse(): NextResponse {
  return { workflow: undefined };
}

export const NextResponse: MessageFns<NextResponse> = {
  encode(message: NextResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.workflow !== undefined) {
      Workflow.encode(message.workflow, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NextResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNextResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.workflow = Workflow.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NextResponse {
    return { workflow: isSet(object.workflow) ? Workflow.fromJSON(object.workflow) : undefined };
  },

  toJSON(message: NextResponse): unknown {
    const obj: any = {};
    if (message.workflow !== undefined) {
      obj.workflow = Workflow.toJSON(message.workflow);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NextResponse>, I>>(base?: I): NextResponse {
    return NextResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NextResponse>, I>>(object: I): NextResponse {
    const message = createBaseNextResponse();
    message.workflow = (object.workflow !== undefined && object.workflow !== null)
      ? Workflow.fromPartial(object.workflow)
      : undefined;
    return message;
  },
};

function createBaseRegisterAgentResponse(): RegisterAgentResponse {
  return { agentId: "" };
}

export const RegisterAgentResponse: MessageFns<RegisterAgentResponse> = {
  encode(message: RegisterAgentResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.agentId !== undefined && message.agentId !== "") {
      writer.uint32(10).string(message.agentId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegisterAgentResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegisterAgentResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.agentId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RegisterAgentResponse {
    return {
      agentId: isSet(object.agentId)
        ? globalThis.String(object.agentId)
        : isSet(object.agent_id)
        ? globalThis.String(object.agent_id)
        : "",
    };
  },

  toJSON(message: RegisterAgentResponse): unknown {
    const obj: any = {};
    if (message.agentId !== undefined && message.agentId !== "") {
      obj.agentId = message.agentId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RegisterAgentResponse>, I>>(base?: I): RegisterAgentResponse {
    return RegisterAgentResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RegisterAgentResponse>, I>>(object: I): RegisterAgentResponse {
    const message = createBaseRegisterAgentResponse();
    message.agentId = object.agentId ?? "";
    return message;
  },
};

function createBaseWaitResponse(): WaitResponse {
  return { canceled: false };
}

export const WaitResponse: MessageFns<WaitResponse> = {
  encode(message: WaitResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.canceled !== undefined && message.canceled !== false) {
      writer.uint32(8).bool(message.canceled);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): WaitResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseWaitResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.canceled = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): WaitResponse {
    return { canceled: isSet(object.canceled) ? globalThis.Boolean(object.canceled) : false };
  },

  toJSON(message: WaitResponse): unknown {
    const obj: any = {};
    if (message.canceled !== undefined && message.canceled !== false) {
      obj.canceled = message.canceled;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<WaitResponse>, I>>(base?: I): WaitResponse {
    return WaitResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<WaitResponse>, I>>(object: I): WaitResponse {
    const message = createBaseWaitResponse();
    message.canceled = object.canceled ?? false;
    return message;
  },
};

function createBaseAuthRequest(): AuthRequest {
  return { agentToken: "", agentId: "", hostname: "" };
}

export const AuthRequest: MessageFns<AuthRequest> = {
  encode(message: AuthRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.agentToken !== undefined && message.agentToken !== "") {
      writer.uint32(10).string(message.agentToken);
    }
    if (message.agentId !== undefined && message.agentId !== "") {
      writer.uint32(18).string(message.agentId);
    }
    if (message.hostname !== undefined && message.hostname !== "") {
      writer.uint32(26).string(message.hostname);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AuthRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuthRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.agentToken = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.agentId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.hostname = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AuthRequest {
    return {
      agentToken: isSet(object.agentToken)
        ? globalThis.String(object.agentToken)
        : isSet(object.agent_token)
        ? globalThis.String(object.agent_token)
        : "",
      agentId: isSet(object.agentId)
        ? globalThis.String(object.agentId)
        : isSet(object.agent_id)
        ? globalThis.String(object.agent_id)
        : "",
      hostname: isSet(object.hostname) ? globalThis.String(object.hostname) : "",
    };
  },

  toJSON(message: AuthRequest): unknown {
    const obj: any = {};
    if (message.agentToken !== undefined && message.agentToken !== "") {
      obj.agentToken = message.agentToken;
    }
    if (message.agentId !== undefined && message.agentId !== "") {
      obj.agentId = message.agentId;
    }
    if (message.hostname !== undefined && message.hostname !== "") {
      obj.hostname = message.hostname;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AuthRequest>, I>>(base?: I): AuthRequest {
    return AuthRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AuthRequest>, I>>(object: I): AuthRequest {
    const message = createBaseAuthRequest();
    message.agentToken = object.agentToken ?? "";
    message.agentId = object.agentId ?? "";
    message.hostname = object.hostname ?? "";
    return message;
  },
};

function createBaseAuthResponse(): AuthResponse {
  return { status: "", agentId: "", accessToken: "" };
}

export const AuthResponse: MessageFns<AuthResponse> = {
  encode(message: AuthResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.status !== undefined && message.status !== "") {
      writer.uint32(10).string(message.status);
    }
    if (message.agentId !== undefined && message.agentId !== "") {
      writer.uint32(18).string(message.agentId);
    }
    if (message.accessToken !== undefined && message.accessToken !== "") {
      writer.uint32(26).string(message.accessToken);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AuthResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuthResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.agentId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.accessToken = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AuthResponse {
    return {
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      agentId: isSet(object.agentId)
        ? globalThis.String(object.agentId)
        : isSet(object.agent_id)
        ? globalThis.String(object.agent_id)
        : "",
      accessToken: isSet(object.accessToken)
        ? globalThis.String(object.accessToken)
        : isSet(object.access_token)
        ? globalThis.String(object.access_token)
        : "",
    };
  },

  toJSON(message: AuthResponse): unknown {
    const obj: any = {};
    if (message.status !== undefined && message.status !== "") {
      obj.status = message.status;
    }
    if (message.agentId !== undefined && message.agentId !== "") {
      obj.agentId = message.agentId;
    }
    if (message.accessToken !== undefined && message.accessToken !== "") {
      obj.accessToken = message.accessToken;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AuthResponse>, I>>(base?: I): AuthResponse {
    return AuthResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AuthResponse>, I>>(object: I): AuthResponse {
    const message = createBaseAuthResponse();
    message.status = object.status ?? "";
    message.agentId = object.agentId ?? "";
    message.accessToken = object.accessToken ?? "";
    return message;
  },
};

function createBaseStreamOptions(): StreamOptions {
  return { filter: undefined };
}

export const StreamOptions: MessageFns<StreamOptions> = {
  encode(message: StreamOptions, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.filter !== undefined) {
      Filter.encode(message.filter, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StreamOptions {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStreamOptions();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.filter = Filter.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StreamOptions {
    return { filter: isSet(object.filter) ? Filter.fromJSON(object.filter) : undefined };
  },

  toJSON(message: StreamOptions): unknown {
    const obj: any = {};
    if (message.filter !== undefined) {
      obj.filter = Filter.toJSON(message.filter);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StreamOptions>, I>>(base?: I): StreamOptions {
    return StreamOptions.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StreamOptions>, I>>(object: I): StreamOptions {
    const message = createBaseStreamOptions();
    message.filter = (object.filter !== undefined && object.filter !== null)
      ? Filter.fromPartial(object.filter)
      : undefined;
    return message;
  },
};

function createBaseStatusUpdate(): StatusUpdate {
  return { stepUuid: "", time: 0, type: 0, data: Buffer.alloc(0) };
}

export const StatusUpdate: MessageFns<StatusUpdate> = {
  encode(message: StatusUpdate, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.stepUuid !== undefined && message.stepUuid !== "") {
      writer.uint32(10).string(message.stepUuid);
    }
    if (message.time !== undefined && message.time !== 0) {
      writer.uint32(16).int64(message.time);
    }
    if (message.type !== undefined && message.type !== 0) {
      writer.uint32(24).int32(message.type);
    }
    if (message.data !== undefined && message.data.length !== 0) {
      writer.uint32(34).bytes(message.data);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StatusUpdate {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStatusUpdate();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.stepUuid = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.time = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.type = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.data = Buffer.from(reader.bytes());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StatusUpdate {
    return {
      stepUuid: isSet(object.stepUuid)
        ? globalThis.String(object.stepUuid)
        : isSet(object.step_uuid)
        ? globalThis.String(object.step_uuid)
        : "",
      time: isSet(object.time) ? globalThis.Number(object.time) : 0,
      type: isSet(object.type) ? globalThis.Number(object.type) : 0,
      data: isSet(object.data) ? Buffer.from(bytesFromBase64(object.data)) : Buffer.alloc(0),
    };
  },

  toJSON(message: StatusUpdate): unknown {
    const obj: any = {};
    if (message.stepUuid !== undefined && message.stepUuid !== "") {
      obj.stepUuid = message.stepUuid;
    }
    if (message.time !== undefined && message.time !== 0) {
      obj.time = Math.round(message.time);
    }
    if (message.type !== undefined && message.type !== 0) {
      obj.type = Math.round(message.type);
    }
    if (message.data !== undefined && message.data.length !== 0) {
      obj.data = base64FromBytes(message.data);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<StatusUpdate>, I>>(base?: I): StatusUpdate {
    return StatusUpdate.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<StatusUpdate>, I>>(object: I): StatusUpdate {
    const message = createBaseStatusUpdate();
    message.stepUuid = object.stepUuid ?? "";
    message.time = object.time ?? 0;
    message.type = object.type ?? 0;
    message.data = object.data ?? Buffer.alloc(0);
    return message;
  },
};

/** Woodpecker Server Service */
export type WoodpeckerService = typeof WoodpeckerService;
export const WoodpeckerService = {
  version: {
    path: "/proto.Woodpecker/Version",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: Empty): Buffer => Buffer.from(Empty.encode(value).finish()),
    requestDeserialize: (value: Buffer): Empty => Empty.decode(value),
    responseSerialize: (value: VersionResponse): Buffer => Buffer.from(VersionResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): VersionResponse => VersionResponse.decode(value),
  },
  next: {
    path: "/proto.Woodpecker/Next",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: NextRequest): Buffer => Buffer.from(NextRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): NextRequest => NextRequest.decode(value),
    responseSerialize: (value: NextResponse): Buffer => Buffer.from(NextResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): NextResponse => NextResponse.decode(value),
  },
  init: {
    path: "/proto.Woodpecker/Init",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: InitRequest): Buffer => Buffer.from(InitRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): InitRequest => InitRequest.decode(value),
    responseSerialize: (value: Empty): Buffer => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer): Empty => Empty.decode(value),
  },
  wait: {
    path: "/proto.Woodpecker/Wait",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: WaitRequest): Buffer => Buffer.from(WaitRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): WaitRequest => WaitRequest.decode(value),
    responseSerialize: (value: WaitResponse): Buffer => Buffer.from(WaitResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): WaitResponse => WaitResponse.decode(value),
  },
  done: {
    path: "/proto.Woodpecker/Done",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: DoneRequest): Buffer => Buffer.from(DoneRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): DoneRequest => DoneRequest.decode(value),
    responseSerialize: (value: Empty): Buffer => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer): Empty => Empty.decode(value),
  },
  extend: {
    path: "/proto.Woodpecker/Extend",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ExtendRequest): Buffer => Buffer.from(ExtendRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ExtendRequest => ExtendRequest.decode(value),
    responseSerialize: (value: Empty): Buffer => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer): Empty => Empty.decode(value),
  },
  update: {
    path: "/proto.Woodpecker/Update",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UpdateRequest): Buffer => Buffer.from(UpdateRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateRequest => UpdateRequest.decode(value),
    responseSerialize: (value: Empty): Buffer => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer): Empty => Empty.decode(value),
  },
  log: {
    path: "/proto.Woodpecker/Log",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: LogRequest): Buffer => Buffer.from(LogRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): LogRequest => LogRequest.decode(value),
    responseSerialize: (value: Empty): Buffer => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer): Empty => Empty.decode(value),
  },
  registerAgent: {
    path: "/proto.Woodpecker/RegisterAgent",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: RegisterAgentRequest): Buffer => Buffer.from(RegisterAgentRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): RegisterAgentRequest => RegisterAgentRequest.decode(value),
    responseSerialize: (value: RegisterAgentResponse): Buffer =>
      Buffer.from(RegisterAgentResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): RegisterAgentResponse => RegisterAgentResponse.decode(value),
  },
  unregisterAgent: {
    path: "/proto.Woodpecker/UnregisterAgent",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: Empty): Buffer => Buffer.from(Empty.encode(value).finish()),
    requestDeserialize: (value: Buffer): Empty => Empty.decode(value),
    responseSerialize: (value: Empty): Buffer => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer): Empty => Empty.decode(value),
  },
  reportHealth: {
    path: "/proto.Woodpecker/ReportHealth",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ReportHealthRequest): Buffer => Buffer.from(ReportHealthRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ReportHealthRequest => ReportHealthRequest.decode(value),
    responseSerialize: (value: Empty): Buffer => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer): Empty => Empty.decode(value),
  },
  /** New Streaming RPCs */
  streamJobs: {
    path: "/proto.Woodpecker/StreamJobs",
    requestStream: false,
    responseStream: true,
    requestSerialize: (value: StreamOptions): Buffer => Buffer.from(StreamOptions.encode(value).finish()),
    requestDeserialize: (value: Buffer): StreamOptions => StreamOptions.decode(value),
    responseSerialize: (value: Workflow): Buffer => Buffer.from(Workflow.encode(value).finish()),
    responseDeserialize: (value: Buffer): Workflow => Workflow.decode(value),
  },
  submitStatus: {
    path: "/proto.Woodpecker/SubmitStatus",
    requestStream: true,
    responseStream: false,
    requestSerialize: (value: StatusUpdate): Buffer => Buffer.from(StatusUpdate.encode(value).finish()),
    requestDeserialize: (value: Buffer): StatusUpdate => StatusUpdate.decode(value),
    responseSerialize: (value: Empty): Buffer => Buffer.from(Empty.encode(value).finish()),
    responseDeserialize: (value: Buffer): Empty => Empty.decode(value),
  },
} as const;

export interface WoodpeckerServer extends UntypedServiceImplementation {
  version: handleUnaryCall<Empty, VersionResponse>;
  next: handleUnaryCall<NextRequest, NextResponse>;
  init: handleUnaryCall<InitRequest, Empty>;
  wait: handleUnaryCall<WaitRequest, WaitResponse>;
  done: handleUnaryCall<DoneRequest, Empty>;
  extend: handleUnaryCall<ExtendRequest, Empty>;
  update: handleUnaryCall<UpdateRequest, Empty>;
  log: handleUnaryCall<LogRequest, Empty>;
  registerAgent: handleUnaryCall<RegisterAgentRequest, RegisterAgentResponse>;
  unregisterAgent: handleUnaryCall<Empty, Empty>;
  reportHealth: handleUnaryCall<ReportHealthRequest, Empty>;
  /** New Streaming RPCs */
  streamJobs: handleServerStreamingCall<StreamOptions, Workflow>;
  submitStatus: handleClientStreamingCall<StatusUpdate, Empty>;
}

export interface WoodpeckerClient extends Client {
  version(request: Empty, callback: (error: ServiceError | null, response: VersionResponse) => void): ClientUnaryCall;
  version(
    request: Empty,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: VersionResponse) => void,
  ): ClientUnaryCall;
  version(
    request: Empty,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: VersionResponse) => void,
  ): ClientUnaryCall;
  next(request: NextRequest, callback: (error: ServiceError | null, response: NextResponse) => void): ClientUnaryCall;
  next(
    request: NextRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: NextResponse) => void,
  ): ClientUnaryCall;
  next(
    request: NextRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: NextResponse) => void,
  ): ClientUnaryCall;
  init(request: InitRequest, callback: (error: ServiceError | null, response: Empty) => void): ClientUnaryCall;
  init(
    request: InitRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  init(
    request: InitRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  wait(request: WaitRequest, callback: (error: ServiceError | null, response: WaitResponse) => void): ClientUnaryCall;
  wait(
    request: WaitRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: WaitResponse) => void,
  ): ClientUnaryCall;
  wait(
    request: WaitRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: WaitResponse) => void,
  ): ClientUnaryCall;
  done(request: DoneRequest, callback: (error: ServiceError | null, response: Empty) => void): ClientUnaryCall;
  done(
    request: DoneRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  done(
    request: DoneRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  extend(request: ExtendRequest, callback: (error: ServiceError | null, response: Empty) => void): ClientUnaryCall;
  extend(
    request: ExtendRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  extend(
    request: ExtendRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  update(request: UpdateRequest, callback: (error: ServiceError | null, response: Empty) => void): ClientUnaryCall;
  update(
    request: UpdateRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  update(
    request: UpdateRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  log(request: LogRequest, callback: (error: ServiceError | null, response: Empty) => void): ClientUnaryCall;
  log(
    request: LogRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  log(
    request: LogRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  registerAgent(
    request: RegisterAgentRequest,
    callback: (error: ServiceError | null, response: RegisterAgentResponse) => void,
  ): ClientUnaryCall;
  registerAgent(
    request: RegisterAgentRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: RegisterAgentResponse) => void,
  ): ClientUnaryCall;
  registerAgent(
    request: RegisterAgentRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: RegisterAgentResponse) => void,
  ): ClientUnaryCall;
  unregisterAgent(request: Empty, callback: (error: ServiceError | null, response: Empty) => void): ClientUnaryCall;
  unregisterAgent(
    request: Empty,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  unregisterAgent(
    request: Empty,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  reportHealth(
    request: ReportHealthRequest,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  reportHealth(
    request: ReportHealthRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  reportHealth(
    request: ReportHealthRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientUnaryCall;
  /** New Streaming RPCs */
  streamJobs(request: StreamOptions, options?: Partial<CallOptions>): ClientReadableStream<Workflow>;
  streamJobs(
    request: StreamOptions,
    metadata?: Metadata,
    options?: Partial<CallOptions>,
  ): ClientReadableStream<Workflow>;
  submitStatus(callback: (error: ServiceError | null, response: Empty) => void): ClientWritableStream<StatusUpdate>;
  submitStatus(
    metadata: Metadata,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientWritableStream<StatusUpdate>;
  submitStatus(
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientWritableStream<StatusUpdate>;
  submitStatus(
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: Empty) => void,
  ): ClientWritableStream<StatusUpdate>;
}

export const WoodpeckerClient = makeGenericClientConstructor(WoodpeckerService, "proto.Woodpecker") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): WoodpeckerClient;
  service: typeof WoodpeckerService;
  serviceName: string;
};

export type WoodpeckerAuthService = typeof WoodpeckerAuthService;
export const WoodpeckerAuthService = {
  auth: {
    path: "/proto.WoodpeckerAuth/Auth",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: AuthRequest): Buffer => Buffer.from(AuthRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): AuthRequest => AuthRequest.decode(value),
    responseSerialize: (value: AuthResponse): Buffer => Buffer.from(AuthResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): AuthResponse => AuthResponse.decode(value),
  },
} as const;

export interface WoodpeckerAuthServer extends UntypedServiceImplementation {
  auth: handleUnaryCall<AuthRequest, AuthResponse>;
}

export interface WoodpeckerAuthClient extends Client {
  auth(request: AuthRequest, callback: (error: ServiceError | null, response: AuthResponse) => void): ClientUnaryCall;
  auth(
    request: AuthRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: AuthResponse) => void,
  ): ClientUnaryCall;
  auth(
    request: AuthRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: AuthResponse) => void,
  ): ClientUnaryCall;
}

export const WoodpeckerAuthClient = makeGenericClientConstructor(
  WoodpeckerAuthService,
  "proto.WoodpeckerAuth",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): WoodpeckerAuthClient;
  service: typeof WoodpeckerAuthService;
  serviceName: string;
};

function bytesFromBase64(b64: string): Uint8Array {
  return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
}

function base64FromBytes(arr: Uint8Array): string {
  return globalThis.Buffer.from(arr).toString("base64");
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
