// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: app/v1/account.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { StringValue } from "../../google/protobuf/wrappers";
import { MessageResponse, Notification, Preferences, User } from "./common";

export const protobufPackage = "stream.app.v1";

export interface GetMeRequest {
}

export interface GetMeResponse {
  user?: User | undefined;
}

export interface UpdateMeRequest {
  username?: string | undefined;
  email?: string | undefined;
  language?: string | undefined;
  locale?: string | undefined;
  telegramId?: string | undefined;
}

export interface UpdateMeResponse {
  user?: User | undefined;
}

export interface DeleteMeRequest {
}

export interface ClearMyDataRequest {
}

export interface GetPreferencesRequest {
}

export interface GetPreferencesResponse {
  preferences?: Preferences | undefined;
}

export interface UpdatePreferencesRequest {
  emailNotifications?: boolean | undefined;
  pushNotifications?: boolean | undefined;
  marketingNotifications?: boolean | undefined;
  telegramNotifications?: boolean | undefined;
  autoplay?: boolean | undefined;
  loop?: boolean | undefined;
  muted?: boolean | undefined;
  showControls?: boolean | undefined;
  pip?: boolean | undefined;
  airplay?: boolean | undefined;
  chromecast?: boolean | undefined;
  language?: string | undefined;
  locale?: string | undefined;
}

export interface UpdatePreferencesResponse {
  preferences?: Preferences | undefined;
}

export interface GetUsageRequest {
}

export interface GetUsageResponse {
  userId?: string | undefined;
  totalVideos?: number | undefined;
  totalStorage?: number | undefined;
}

export interface ListNotificationsRequest {
}

export interface ListNotificationsResponse {
  notifications?: Notification[] | undefined;
}

export interface MarkNotificationReadRequest {
  id?: string | undefined;
}

export interface MarkAllNotificationsReadRequest {
}

export interface DeleteNotificationRequest {
  id?: string | undefined;
}

export interface ClearNotificationsRequest {
}

function createBaseGetMeRequest(): GetMeRequest {
  return {};
}

export const GetMeRequest: MessageFns<GetMeRequest> = {
  encode(_: GetMeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetMeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetMeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetMeRequest {
    return {};
  },

  toJSON(_: GetMeRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetMeRequest>, I>>(base?: I): GetMeRequest {
    return GetMeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetMeRequest>, I>>(_: I): GetMeRequest {
    const message = createBaseGetMeRequest();
    return message;
  },
};

function createBaseGetMeResponse(): GetMeResponse {
  return { user: undefined };
}

export const GetMeResponse: MessageFns<GetMeResponse> = {
  encode(message: GetMeResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user !== undefined) {
      User.encode(message.user, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetMeResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetMeResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user = User.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetMeResponse {
    return { user: isSet(object.user) ? User.fromJSON(object.user) : undefined };
  },

  toJSON(message: GetMeResponse): unknown {
    const obj: any = {};
    if (message.user !== undefined) {
      obj.user = User.toJSON(message.user);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetMeResponse>, I>>(base?: I): GetMeResponse {
    return GetMeResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetMeResponse>, I>>(object: I): GetMeResponse {
    const message = createBaseGetMeResponse();
    message.user = (object.user !== undefined && object.user !== null) ? User.fromPartial(object.user) : undefined;
    return message;
  },
};

function createBaseUpdateMeRequest(): UpdateMeRequest {
  return { username: undefined, email: undefined, language: undefined, locale: undefined, telegramId: undefined };
}

export const UpdateMeRequest: MessageFns<UpdateMeRequest> = {
  encode(message: UpdateMeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.username !== undefined) {
      writer.uint32(10).string(message.username);
    }
    if (message.email !== undefined) {
      writer.uint32(18).string(message.email);
    }
    if (message.language !== undefined) {
      writer.uint32(26).string(message.language);
    }
    if (message.locale !== undefined) {
      writer.uint32(34).string(message.locale);
    }
    if (message.telegramId !== undefined) {
      writer.uint32(42).string(message.telegramId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateMeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateMeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.language = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.locale = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.telegramId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateMeRequest {
    return {
      username: isSet(object.username) ? globalThis.String(object.username) : undefined,
      email: isSet(object.email) ? globalThis.String(object.email) : undefined,
      language: isSet(object.language) ? globalThis.String(object.language) : undefined,
      locale: isSet(object.locale) ? globalThis.String(object.locale) : undefined,
      telegramId: isSet(object.telegramId)
        ? globalThis.String(object.telegramId)
        : isSet(object.telegram_id)
        ? globalThis.String(object.telegram_id)
        : undefined,
    };
  },

  toJSON(message: UpdateMeRequest): unknown {
    const obj: any = {};
    if (message.username !== undefined) {
      obj.username = message.username;
    }
    if (message.email !== undefined) {
      obj.email = message.email;
    }
    if (message.language !== undefined) {
      obj.language = message.language;
    }
    if (message.locale !== undefined) {
      obj.locale = message.locale;
    }
    if (message.telegramId !== undefined) {
      obj.telegramId = message.telegramId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateMeRequest>, I>>(base?: I): UpdateMeRequest {
    return UpdateMeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateMeRequest>, I>>(object: I): UpdateMeRequest {
    const message = createBaseUpdateMeRequest();
    message.username = object.username ?? undefined;
    message.email = object.email ?? undefined;
    message.language = object.language ?? undefined;
    message.locale = object.locale ?? undefined;
    message.telegramId = object.telegramId ?? undefined;
    return message;
  },
};

function createBaseUpdateMeResponse(): UpdateMeResponse {
  return { user: undefined };
}

export const UpdateMeResponse: MessageFns<UpdateMeResponse> = {
  encode(message: UpdateMeResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user !== undefined) {
      User.encode(message.user, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateMeResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateMeResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user = User.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateMeResponse {
    return { user: isSet(object.user) ? User.fromJSON(object.user) : undefined };
  },

  toJSON(message: UpdateMeResponse): unknown {
    const obj: any = {};
    if (message.user !== undefined) {
      obj.user = User.toJSON(message.user);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateMeResponse>, I>>(base?: I): UpdateMeResponse {
    return UpdateMeResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateMeResponse>, I>>(object: I): UpdateMeResponse {
    const message = createBaseUpdateMeResponse();
    message.user = (object.user !== undefined && object.user !== null) ? User.fromPartial(object.user) : undefined;
    return message;
  },
};

function createBaseDeleteMeRequest(): DeleteMeRequest {
  return {};
}

export const DeleteMeRequest: MessageFns<DeleteMeRequest> = {
  encode(_: DeleteMeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteMeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteMeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): DeleteMeRequest {
    return {};
  },

  toJSON(_: DeleteMeRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteMeRequest>, I>>(base?: I): DeleteMeRequest {
    return DeleteMeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteMeRequest>, I>>(_: I): DeleteMeRequest {
    const message = createBaseDeleteMeRequest();
    return message;
  },
};

function createBaseClearMyDataRequest(): ClearMyDataRequest {
  return {};
}

export const ClearMyDataRequest: MessageFns<ClearMyDataRequest> = {
  encode(_: ClearMyDataRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClearMyDataRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClearMyDataRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): ClearMyDataRequest {
    return {};
  },

  toJSON(_: ClearMyDataRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ClearMyDataRequest>, I>>(base?: I): ClearMyDataRequest {
    return ClearMyDataRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ClearMyDataRequest>, I>>(_: I): ClearMyDataRequest {
    const message = createBaseClearMyDataRequest();
    return message;
  },
};

function createBaseGetPreferencesRequest(): GetPreferencesRequest {
  return {};
}

export const GetPreferencesRequest: MessageFns<GetPreferencesRequest> = {
  encode(_: GetPreferencesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPreferencesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPreferencesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetPreferencesRequest {
    return {};
  },

  toJSON(_: GetPreferencesRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetPreferencesRequest>, I>>(base?: I): GetPreferencesRequest {
    return GetPreferencesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPreferencesRequest>, I>>(_: I): GetPreferencesRequest {
    const message = createBaseGetPreferencesRequest();
    return message;
  },
};

function createBaseGetPreferencesResponse(): GetPreferencesResponse {
  return { preferences: undefined };
}

export const GetPreferencesResponse: MessageFns<GetPreferencesResponse> = {
  encode(message: GetPreferencesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.preferences !== undefined) {
      Preferences.encode(message.preferences, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPreferencesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPreferencesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.preferences = Preferences.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetPreferencesResponse {
    return { preferences: isSet(object.preferences) ? Preferences.fromJSON(object.preferences) : undefined };
  },

  toJSON(message: GetPreferencesResponse): unknown {
    const obj: any = {};
    if (message.preferences !== undefined) {
      obj.preferences = Preferences.toJSON(message.preferences);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetPreferencesResponse>, I>>(base?: I): GetPreferencesResponse {
    return GetPreferencesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPreferencesResponse>, I>>(object: I): GetPreferencesResponse {
    const message = createBaseGetPreferencesResponse();
    message.preferences = (object.preferences !== undefined && object.preferences !== null)
      ? Preferences.fromPartial(object.preferences)
      : undefined;
    return message;
  },
};

function createBaseUpdatePreferencesRequest(): UpdatePreferencesRequest {
  return {
    emailNotifications: undefined,
    pushNotifications: undefined,
    marketingNotifications: undefined,
    telegramNotifications: undefined,
    autoplay: undefined,
    loop: undefined,
    muted: undefined,
    showControls: undefined,
    pip: undefined,
    airplay: undefined,
    chromecast: undefined,
    language: undefined,
    locale: undefined,
  };
}

export const UpdatePreferencesRequest: MessageFns<UpdatePreferencesRequest> = {
  encode(message: UpdatePreferencesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.emailNotifications !== undefined) {
      writer.uint32(8).bool(message.emailNotifications);
    }
    if (message.pushNotifications !== undefined) {
      writer.uint32(16).bool(message.pushNotifications);
    }
    if (message.marketingNotifications !== undefined) {
      writer.uint32(24).bool(message.marketingNotifications);
    }
    if (message.telegramNotifications !== undefined) {
      writer.uint32(32).bool(message.telegramNotifications);
    }
    if (message.autoplay !== undefined) {
      writer.uint32(40).bool(message.autoplay);
    }
    if (message.loop !== undefined) {
      writer.uint32(48).bool(message.loop);
    }
    if (message.muted !== undefined) {
      writer.uint32(56).bool(message.muted);
    }
    if (message.showControls !== undefined) {
      writer.uint32(64).bool(message.showControls);
    }
    if (message.pip !== undefined) {
      writer.uint32(72).bool(message.pip);
    }
    if (message.airplay !== undefined) {
      writer.uint32(80).bool(message.airplay);
    }
    if (message.chromecast !== undefined) {
      writer.uint32(88).bool(message.chromecast);
    }
    if (message.language !== undefined) {
      writer.uint32(98).string(message.language);
    }
    if (message.locale !== undefined) {
      writer.uint32(106).string(message.locale);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdatePreferencesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdatePreferencesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.emailNotifications = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.pushNotifications = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.marketingNotifications = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.telegramNotifications = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.autoplay = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.loop = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.muted = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.showControls = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.pip = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.airplay = reader.bool();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.chromecast = reader.bool();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.language = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.locale = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdatePreferencesRequest {
    return {
      emailNotifications: isSet(object.emailNotifications)
        ? globalThis.Boolean(object.emailNotifications)
        : isSet(object.email_notifications)
        ? globalThis.Boolean(object.email_notifications)
        : undefined,
      pushNotifications: isSet(object.pushNotifications)
        ? globalThis.Boolean(object.pushNotifications)
        : isSet(object.push_notifications)
        ? globalThis.Boolean(object.push_notifications)
        : undefined,
      marketingNotifications: isSet(object.marketingNotifications)
        ? globalThis.Boolean(object.marketingNotifications)
        : isSet(object.marketing_notifications)
        ? globalThis.Boolean(object.marketing_notifications)
        : undefined,
      telegramNotifications: isSet(object.telegramNotifications)
        ? globalThis.Boolean(object.telegramNotifications)
        : isSet(object.telegram_notifications)
        ? globalThis.Boolean(object.telegram_notifications)
        : undefined,
      autoplay: isSet(object.autoplay) ? globalThis.Boolean(object.autoplay) : undefined,
      loop: isSet(object.loop) ? globalThis.Boolean(object.loop) : undefined,
      muted: isSet(object.muted) ? globalThis.Boolean(object.muted) : undefined,
      showControls: isSet(object.showControls)
        ? globalThis.Boolean(object.showControls)
        : isSet(object.show_controls)
        ? globalThis.Boolean(object.show_controls)
        : undefined,
      pip: isSet(object.pip) ? globalThis.Boolean(object.pip) : undefined,
      airplay: isSet(object.airplay) ? globalThis.Boolean(object.airplay) : undefined,
      chromecast: isSet(object.chromecast) ? globalThis.Boolean(object.chromecast) : undefined,
      language: isSet(object.language) ? globalThis.String(object.language) : undefined,
      locale: isSet(object.locale) ? globalThis.String(object.locale) : undefined,
    };
  },

  toJSON(message: UpdatePreferencesRequest): unknown {
    const obj: any = {};
    if (message.emailNotifications !== undefined) {
      obj.emailNotifications = message.emailNotifications;
    }
    if (message.pushNotifications !== undefined) {
      obj.pushNotifications = message.pushNotifications;
    }
    if (message.marketingNotifications !== undefined) {
      obj.marketingNotifications = message.marketingNotifications;
    }
    if (message.telegramNotifications !== undefined) {
      obj.telegramNotifications = message.telegramNotifications;
    }
    if (message.autoplay !== undefined) {
      obj.autoplay = message.autoplay;
    }
    if (message.loop !== undefined) {
      obj.loop = message.loop;
    }
    if (message.muted !== undefined) {
      obj.muted = message.muted;
    }
    if (message.showControls !== undefined) {
      obj.showControls = message.showControls;
    }
    if (message.pip !== undefined) {
      obj.pip = message.pip;
    }
    if (message.airplay !== undefined) {
      obj.airplay = message.airplay;
    }
    if (message.chromecast !== undefined) {
      obj.chromecast = message.chromecast;
    }
    if (message.language !== undefined) {
      obj.language = message.language;
    }
    if (message.locale !== undefined) {
      obj.locale = message.locale;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdatePreferencesRequest>, I>>(base?: I): UpdatePreferencesRequest {
    return UpdatePreferencesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdatePreferencesRequest>, I>>(object: I): UpdatePreferencesRequest {
    const message = createBaseUpdatePreferencesRequest();
    message.emailNotifications = object.emailNotifications ?? undefined;
    message.pushNotifications = object.pushNotifications ?? undefined;
    message.marketingNotifications = object.marketingNotifications ?? undefined;
    message.telegramNotifications = object.telegramNotifications ?? undefined;
    message.autoplay = object.autoplay ?? undefined;
    message.loop = object.loop ?? undefined;
    message.muted = object.muted ?? undefined;
    message.showControls = object.showControls ?? undefined;
    message.pip = object.pip ?? undefined;
    message.airplay = object.airplay ?? undefined;
    message.chromecast = object.chromecast ?? undefined;
    message.language = object.language ?? undefined;
    message.locale = object.locale ?? undefined;
    return message;
  },
};

function createBaseUpdatePreferencesResponse(): UpdatePreferencesResponse {
  return { preferences: undefined };
}

export const UpdatePreferencesResponse: MessageFns<UpdatePreferencesResponse> = {
  encode(message: UpdatePreferencesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.preferences !== undefined) {
      Preferences.encode(message.preferences, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdatePreferencesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdatePreferencesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.preferences = Preferences.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdatePreferencesResponse {
    return { preferences: isSet(object.preferences) ? Preferences.fromJSON(object.preferences) : undefined };
  },

  toJSON(message: UpdatePreferencesResponse): unknown {
    const obj: any = {};
    if (message.preferences !== undefined) {
      obj.preferences = Preferences.toJSON(message.preferences);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdatePreferencesResponse>, I>>(base?: I): UpdatePreferencesResponse {
    return UpdatePreferencesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdatePreferencesResponse>, I>>(object: I): UpdatePreferencesResponse {
    const message = createBaseUpdatePreferencesResponse();
    message.preferences = (object.preferences !== undefined && object.preferences !== null)
      ? Preferences.fromPartial(object.preferences)
      : undefined;
    return message;
  },
};

function createBaseGetUsageRequest(): GetUsageRequest {
  return {};
}

export const GetUsageRequest: MessageFns<GetUsageRequest> = {
  encode(_: GetUsageRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUsageRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUsageRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetUsageRequest {
    return {};
  },

  toJSON(_: GetUsageRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetUsageRequest>, I>>(base?: I): GetUsageRequest {
    return GetUsageRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetUsageRequest>, I>>(_: I): GetUsageRequest {
    const message = createBaseGetUsageRequest();
    return message;
  },
};

function createBaseGetUsageResponse(): GetUsageResponse {
  return { userId: "", totalVideos: 0, totalStorage: 0 };
}

export const GetUsageResponse: MessageFns<GetUsageResponse> = {
  encode(message: GetUsageResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== undefined && message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.totalVideos !== undefined && message.totalVideos !== 0) {
      writer.uint32(16).int64(message.totalVideos);
    }
    if (message.totalStorage !== undefined && message.totalStorage !== 0) {
      writer.uint32(24).int64(message.totalStorage);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUsageResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUsageResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.totalVideos = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.totalStorage = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetUsageResponse {
    return {
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      totalVideos: isSet(object.totalVideos)
        ? globalThis.Number(object.totalVideos)
        : isSet(object.total_videos)
        ? globalThis.Number(object.total_videos)
        : 0,
      totalStorage: isSet(object.totalStorage)
        ? globalThis.Number(object.totalStorage)
        : isSet(object.total_storage)
        ? globalThis.Number(object.total_storage)
        : 0,
    };
  },

  toJSON(message: GetUsageResponse): unknown {
    const obj: any = {};
    if (message.userId !== undefined && message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.totalVideos !== undefined && message.totalVideos !== 0) {
      obj.totalVideos = Math.round(message.totalVideos);
    }
    if (message.totalStorage !== undefined && message.totalStorage !== 0) {
      obj.totalStorage = Math.round(message.totalStorage);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetUsageResponse>, I>>(base?: I): GetUsageResponse {
    return GetUsageResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetUsageResponse>, I>>(object: I): GetUsageResponse {
    const message = createBaseGetUsageResponse();
    message.userId = object.userId ?? "";
    message.totalVideos = object.totalVideos ?? 0;
    message.totalStorage = object.totalStorage ?? 0;
    return message;
  },
};

function createBaseListNotificationsRequest(): ListNotificationsRequest {
  return {};
}

export const ListNotificationsRequest: MessageFns<ListNotificationsRequest> = {
  encode(_: ListNotificationsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListNotificationsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListNotificationsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): ListNotificationsRequest {
    return {};
  },

  toJSON(_: ListNotificationsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ListNotificationsRequest>, I>>(base?: I): ListNotificationsRequest {
    return ListNotificationsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListNotificationsRequest>, I>>(_: I): ListNotificationsRequest {
    const message = createBaseListNotificationsRequest();
    return message;
  },
};

function createBaseListNotificationsResponse(): ListNotificationsResponse {
  return { notifications: [] };
}

export const ListNotificationsResponse: MessageFns<ListNotificationsResponse> = {
  encode(message: ListNotificationsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.notifications !== undefined && message.notifications.length !== 0) {
      for (const v of message.notifications) {
        Notification.encode(v!, writer.uint32(10).fork()).join();
      }
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListNotificationsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListNotificationsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          const el = Notification.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.notifications!.push(el);
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListNotificationsResponse {
    return {
      notifications: globalThis.Array.isArray(object?.notifications)
        ? object.notifications.map((e: any) => Notification.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ListNotificationsResponse): unknown {
    const obj: any = {};
    if (message.notifications?.length) {
      obj.notifications = message.notifications.map((e) => Notification.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListNotificationsResponse>, I>>(base?: I): ListNotificationsResponse {
    return ListNotificationsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListNotificationsResponse>, I>>(object: I): ListNotificationsResponse {
    const message = createBaseListNotificationsResponse();
    message.notifications = object.notifications?.map((e) => Notification.fromPartial(e)) || [];
    return message;
  },
};

function createBaseMarkNotificationReadRequest(): MarkNotificationReadRequest {
  return { id: "" };
}

export const MarkNotificationReadRequest: MessageFns<MarkNotificationReadRequest> = {
  encode(message: MarkNotificationReadRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined && message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MarkNotificationReadRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMarkNotificationReadRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MarkNotificationReadRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: MarkNotificationReadRequest): unknown {
    const obj: any = {};
    if (message.id !== undefined && message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MarkNotificationReadRequest>, I>>(base?: I): MarkNotificationReadRequest {
    return MarkNotificationReadRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MarkNotificationReadRequest>, I>>(object: I): MarkNotificationReadRequest {
    const message = createBaseMarkNotificationReadRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseMarkAllNotificationsReadRequest(): MarkAllNotificationsReadRequest {
  return {};
}

export const MarkAllNotificationsReadRequest: MessageFns<MarkAllNotificationsReadRequest> = {
  encode(_: MarkAllNotificationsReadRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MarkAllNotificationsReadRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMarkAllNotificationsReadRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): MarkAllNotificationsReadRequest {
    return {};
  },

  toJSON(_: MarkAllNotificationsReadRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<MarkAllNotificationsReadRequest>, I>>(base?: I): MarkAllNotificationsReadRequest {
    return MarkAllNotificationsReadRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MarkAllNotificationsReadRequest>, I>>(_: I): MarkAllNotificationsReadRequest {
    const message = createBaseMarkAllNotificationsReadRequest();
    return message;
  },
};

function createBaseDeleteNotificationRequest(): DeleteNotificationRequest {
  return { id: "" };
}

export const DeleteNotificationRequest: MessageFns<DeleteNotificationRequest> = {
  encode(message: DeleteNotificationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined && message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteNotificationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteNotificationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteNotificationRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: DeleteNotificationRequest): unknown {
    const obj: any = {};
    if (message.id !== undefined && message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteNotificationRequest>, I>>(base?: I): DeleteNotificationRequest {
    return DeleteNotificationRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteNotificationRequest>, I>>(object: I): DeleteNotificationRequest {
    const message = createBaseDeleteNotificationRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseClearNotificationsRequest(): ClearNotificationsRequest {
  return {};
}

export const ClearNotificationsRequest: MessageFns<ClearNotificationsRequest> = {
  encode(_: ClearNotificationsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ClearNotificationsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseClearNotificationsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): ClearNotificationsRequest {
    return {};
  },

  toJSON(_: ClearNotificationsRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ClearNotificationsRequest>, I>>(base?: I): ClearNotificationsRequest {
    return ClearNotificationsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ClearNotificationsRequest>, I>>(_: I): ClearNotificationsRequest {
    const message = createBaseClearNotificationsRequest();
    return message;
  },
};

export type AccountService = typeof AccountService;
export const AccountService = {
  getMe: {
    path: "/stream.app.v1.Account/GetMe",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetMeRequest): Buffer => Buffer.from(GetMeRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetMeRequest => GetMeRequest.decode(value),
    responseSerialize: (value: GetMeResponse): Buffer => Buffer.from(GetMeResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetMeResponse => GetMeResponse.decode(value),
  },
  updateMe: {
    path: "/stream.app.v1.Account/UpdateMe",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UpdateMeRequest): Buffer => Buffer.from(UpdateMeRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateMeRequest => UpdateMeRequest.decode(value),
    responseSerialize: (value: UpdateMeResponse): Buffer => Buffer.from(UpdateMeResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): UpdateMeResponse => UpdateMeResponse.decode(value),
  },
  deleteMe: {
    path: "/stream.app.v1.Account/DeleteMe",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: DeleteMeRequest): Buffer => Buffer.from(DeleteMeRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): DeleteMeRequest => DeleteMeRequest.decode(value),
    responseSerialize: (value: MessageResponse): Buffer => Buffer.from(MessageResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): MessageResponse => MessageResponse.decode(value),
  },
  clearMyData: {
    path: "/stream.app.v1.Account/ClearMyData",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ClearMyDataRequest): Buffer => Buffer.from(ClearMyDataRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ClearMyDataRequest => ClearMyDataRequest.decode(value),
    responseSerialize: (value: MessageResponse): Buffer => Buffer.from(MessageResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): MessageResponse => MessageResponse.decode(value),
  },
  getUserById: {
    path: "/stream.app.v1.Account/GetUserById",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: string | undefined): Buffer =>
      Buffer.from(StringValue.encode({ value: value ?? "" }).finish()),
    requestDeserialize: (value: Buffer): string | undefined => StringValue.decode(value).value,
    responseSerialize: (value: User): Buffer => Buffer.from(User.encode(value).finish()),
    responseDeserialize: (value: Buffer): User => User.decode(value),
  },
  getPreferences: {
    path: "/stream.app.v1.Account/GetPreferences",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetPreferencesRequest): Buffer =>
      Buffer.from(GetPreferencesRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetPreferencesRequest => GetPreferencesRequest.decode(value),
    responseSerialize: (value: GetPreferencesResponse): Buffer =>
      Buffer.from(GetPreferencesResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetPreferencesResponse => GetPreferencesResponse.decode(value),
  },
  updatePreferences: {
    path: "/stream.app.v1.Account/UpdatePreferences",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UpdatePreferencesRequest): Buffer =>
      Buffer.from(UpdatePreferencesRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdatePreferencesRequest => UpdatePreferencesRequest.decode(value),
    responseSerialize: (value: UpdatePreferencesResponse): Buffer =>
      Buffer.from(UpdatePreferencesResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): UpdatePreferencesResponse => UpdatePreferencesResponse.decode(value),
  },
  getUsage: {
    path: "/stream.app.v1.Account/GetUsage",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetUsageRequest): Buffer => Buffer.from(GetUsageRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetUsageRequest => GetUsageRequest.decode(value),
    responseSerialize: (value: GetUsageResponse): Buffer => Buffer.from(GetUsageResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetUsageResponse => GetUsageResponse.decode(value),
  },
} as const;

export interface AccountServer extends UntypedServiceImplementation {
  getMe: handleUnaryCall<GetMeRequest, GetMeResponse>;
  updateMe: handleUnaryCall<UpdateMeRequest, UpdateMeResponse>;
  deleteMe: handleUnaryCall<DeleteMeRequest, MessageResponse>;
  clearMyData: handleUnaryCall<ClearMyDataRequest, MessageResponse>;
  getUserById: handleUnaryCall<string | undefined, User>;
  getPreferences: handleUnaryCall<GetPreferencesRequest, GetPreferencesResponse>;
  updatePreferences: handleUnaryCall<UpdatePreferencesRequest, UpdatePreferencesResponse>;
  getUsage: handleUnaryCall<GetUsageRequest, GetUsageResponse>;
}

export interface AccountClient extends Client {
  getMe(
    request: GetMeRequest,
    callback: (error: ServiceError | null, response: GetMeResponse) => void,
  ): ClientUnaryCall;
  getMe(
    request: GetMeRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetMeResponse) => void,
  ): ClientUnaryCall;
  getMe(
    request: GetMeRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetMeResponse) => void,
  ): ClientUnaryCall;
  updateMe(
    request: UpdateMeRequest,
    callback: (error: ServiceError | null, response: UpdateMeResponse) => void,
  ): ClientUnaryCall;
  updateMe(
    request: UpdateMeRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: UpdateMeResponse) => void,
  ): ClientUnaryCall;
  updateMe(
    request: UpdateMeRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UpdateMeResponse) => void,
  ): ClientUnaryCall;
  deleteMe(
    request: DeleteMeRequest,
    callback: (error: ServiceError | null, response: MessageResponse) => void,
  ): ClientUnaryCall;
  deleteMe(
    request: DeleteMeRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: MessageResponse) => void,
  ): ClientUnaryCall;
  deleteMe(
    request: DeleteMeRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: MessageResponse) => void,
  ): ClientUnaryCall;
  clearMyData(
    request: ClearMyDataRequest,
    callback: (error: ServiceError | null, response: MessageResponse) => void,
  ): ClientUnaryCall;
  clearMyData(
    request: ClearMyDataRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: MessageResponse) => void,
  ): ClientUnaryCall;
  clearMyData(
    request: ClearMyDataRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: MessageResponse) => void,
  ): ClientUnaryCall;
  getUserById(
    request: string | undefined,
    callback: (error: ServiceError | null, response: User) => void,
  ): ClientUnaryCall;
  getUserById(
    request: string | undefined,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: User) => void,
  ): ClientUnaryCall;
  getUserById(
    request: string | undefined,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: User) => void,
  ): ClientUnaryCall;
  getPreferences(
    request: GetPreferencesRequest,
    callback: (error: ServiceError | null, response: GetPreferencesResponse) => void,
  ): ClientUnaryCall;
  getPreferences(
    request: GetPreferencesRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetPreferencesResponse) => void,
  ): ClientUnaryCall;
  getPreferences(
    request: GetPreferencesRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetPreferencesResponse) => void,
  ): ClientUnaryCall;
  updatePreferences(
    request: UpdatePreferencesRequest,
    callback: (error: ServiceError | null, response: UpdatePreferencesResponse) => void,
  ): ClientUnaryCall;
  updatePreferences(
    request: UpdatePreferencesRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: UpdatePreferencesResponse) => void,
  ): ClientUnaryCall;
  updatePreferences(
    request: UpdatePreferencesRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UpdatePreferencesResponse) => void,
  ): ClientUnaryCall;
  getUsage(
    request: GetUsageRequest,
    callback: (error: ServiceError | null, response: GetUsageResponse) => void,
  ): ClientUnaryCall;
  getUsage(
    request: GetUsageRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetUsageResponse) => void,
  ): ClientUnaryCall;
  getUsage(
    request: GetUsageRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetUsageResponse) => void,
  ): ClientUnaryCall;
}

export const AccountClient = makeGenericClientConstructor(AccountService, "stream.app.v1.Account") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): AccountClient;
  service: typeof AccountService;
  serviceName: string;
};

export type NotificationsService = typeof NotificationsService;
export const NotificationsService = {
  listNotifications: {
    path: "/stream.app.v1.Notifications/ListNotifications",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ListNotificationsRequest): Buffer =>
      Buffer.from(ListNotificationsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ListNotificationsRequest => ListNotificationsRequest.decode(value),
    responseSerialize: (value: ListNotificationsResponse): Buffer =>
      Buffer.from(ListNotificationsResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ListNotificationsResponse => ListNotificationsResponse.decode(value),
  },
  markNotificationRead: {
    path: "/stream.app.v1.Notifications/MarkNotificationRead",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: MarkNotificationReadRequest): Buffer =>
      Buffer.from(MarkNotificationReadRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): MarkNotificationReadRequest => MarkNotificationReadRequest.decode(value),
    responseSerialize: (value: MessageResponse): Buffer => Buffer.from(MessageResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): MessageResponse => MessageResponse.decode(value),
  },
  markAllNotificationsRead: {
    path: "/stream.app.v1.Notifications/MarkAllNotificationsRead",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: MarkAllNotificationsReadRequest): Buffer =>
      Buffer.from(MarkAllNotificationsReadRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): MarkAllNotificationsReadRequest =>
      MarkAllNotificationsReadRequest.decode(value),
    responseSerialize: (value: MessageResponse): Buffer => Buffer.from(MessageResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): MessageResponse => MessageResponse.decode(value),
  },
  deleteNotification: {
    path: "/stream.app.v1.Notifications/DeleteNotification",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: DeleteNotificationRequest): Buffer =>
      Buffer.from(DeleteNotificationRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): DeleteNotificationRequest => DeleteNotificationRequest.decode(value),
    responseSerialize: (value: MessageResponse): Buffer => Buffer.from(MessageResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): MessageResponse => MessageResponse.decode(value),
  },
  clearNotifications: {
    path: "/stream.app.v1.Notifications/ClearNotifications",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ClearNotificationsRequest): Buffer =>
      Buffer.from(ClearNotificationsRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ClearNotificationsRequest => ClearNotificationsRequest.decode(value),
    responseSerialize: (value: MessageResponse): Buffer => Buffer.from(MessageResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): MessageResponse => MessageResponse.decode(value),
  },
} as const;

export interface NotificationsServer extends UntypedServiceImplementation {
  listNotifications: handleUnaryCall<ListNotificationsRequest, ListNotificationsResponse>;
  markNotificationRead: handleUnaryCall<MarkNotificationReadRequest, MessageResponse>;
  markAllNotificationsRead: handleUnaryCall<MarkAllNotificationsReadRequest, MessageResponse>;
  deleteNotification: handleUnaryCall<DeleteNotificationRequest, MessageResponse>;
  clearNotifications: handleUnaryCall<ClearNotificationsRequest, MessageResponse>;
}

export interface NotificationsClient extends Client {
  listNotifications(
    request: ListNotificationsRequest,
    callback: (error: ServiceError | null, response: ListNotificationsResponse) => void,
  ): ClientUnaryCall;
  listNotifications(
    request: ListNotificationsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ListNotificationsResponse) => void,
  ): ClientUnaryCall;
  listNotifications(
    request: ListNotificationsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ListNotificationsResponse) => void,
  ): ClientUnaryCall;
  markNotificationRead(
    request: MarkNotificationReadRequest,
    callback: (error: ServiceError | null, response: MessageResponse) => void,
  ): ClientUnaryCall;
  markNotificationRead(
    request: MarkNotificationReadRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: MessageResponse) => void,
  ): ClientUnaryCall;
  markNotificationRead(
    request: MarkNotificationReadRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: MessageResponse) => void,
  ): ClientUnaryCall;
  markAllNotificationsRead(
    request: MarkAllNotificationsReadRequest,
    callback: (error: ServiceError | null, response: MessageResponse) => void,
  ): ClientUnaryCall;
  markAllNotificationsRead(
    request: MarkAllNotificationsReadRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: MessageResponse) => void,
  ): ClientUnaryCall;
  markAllNotificationsRead(
    request: MarkAllNotificationsReadRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: MessageResponse) => void,
  ): ClientUnaryCall;
  deleteNotification(
    request: DeleteNotificationRequest,
    callback: (error: ServiceError | null, response: MessageResponse) => void,
  ): ClientUnaryCall;
  deleteNotification(
    request: DeleteNotificationRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: MessageResponse) => void,
  ): ClientUnaryCall;
  deleteNotification(
    request: DeleteNotificationRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: MessageResponse) => void,
  ): ClientUnaryCall;
  clearNotifications(
    request: ClearNotificationsRequest,
    callback: (error: ServiceError | null, response: MessageResponse) => void,
  ): ClientUnaryCall;
  clearNotifications(
    request: ClearNotificationsRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: MessageResponse) => void,
  ): ClientUnaryCall;
  clearNotifications(
    request: ClearNotificationsRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: MessageResponse) => void,
  ): ClientUnaryCall;
}

export const NotificationsClient = makeGenericClientConstructor(
  NotificationsService,
  "stream.app.v1.Notifications",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): NotificationsClient;
  service: typeof NotificationsService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
