// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: app/v1/videos.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { MessageResponse, Video } from "./common";

export const protobufPackage = "stream.app.v1";

export interface GetUploadUrlRequest {
  filename?: string | undefined;
}

export interface GetUploadUrlResponse {
  uploadUrl?: string | undefined;
  key?: string | undefined;
  fileId?: string | undefined;
}

export interface CreateVideoRequest {
  title?: string | undefined;
  description?: string | undefined;
  url?: string | undefined;
  size?: number | undefined;
  duration?: number | undefined;
  format?: string | undefined;
}

export interface CreateVideoResponse {
  video?: Video | undefined;
}

export interface ListVideosRequest {
  page?: number | undefined;
  limit?: number | undefined;
  search?: string | undefined;
  status?: string | undefined;
}

export interface ListVideosResponse {
  videos?: Video[] | undefined;
  total?: number | undefined;
  page?: number | undefined;
  limit?: number | undefined;
}

export interface GetVideoRequest {
  id?: string | undefined;
}

export interface GetVideoResponse {
  video?: Video | undefined;
}

export interface UpdateVideoRequest {
  id?: string | undefined;
  title?: string | undefined;
  description?: string | undefined;
  url?: string | undefined;
  size?: number | undefined;
  duration?: number | undefined;
  format?: string | undefined;
  status?: string | undefined;
}

export interface UpdateVideoResponse {
  video?: Video | undefined;
}

export interface DeleteVideoRequest {
  id?: string | undefined;
}

function createBaseGetUploadUrlRequest(): GetUploadUrlRequest {
  return { filename: "" };
}

export const GetUploadUrlRequest: MessageFns<GetUploadUrlRequest> = {
  encode(message: GetUploadUrlRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.filename !== undefined && message.filename !== "") {
      writer.uint32(10).string(message.filename);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUploadUrlRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUploadUrlRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.filename = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetUploadUrlRequest {
    return { filename: isSet(object.filename) ? globalThis.String(object.filename) : "" };
  },

  toJSON(message: GetUploadUrlRequest): unknown {
    const obj: any = {};
    if (message.filename !== undefined && message.filename !== "") {
      obj.filename = message.filename;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetUploadUrlRequest>, I>>(base?: I): GetUploadUrlRequest {
    return GetUploadUrlRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetUploadUrlRequest>, I>>(object: I): GetUploadUrlRequest {
    const message = createBaseGetUploadUrlRequest();
    message.filename = object.filename ?? "";
    return message;
  },
};

function createBaseGetUploadUrlResponse(): GetUploadUrlResponse {
  return { uploadUrl: "", key: "", fileId: "" };
}

export const GetUploadUrlResponse: MessageFns<GetUploadUrlResponse> = {
  encode(message: GetUploadUrlResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.uploadUrl !== undefined && message.uploadUrl !== "") {
      writer.uint32(10).string(message.uploadUrl);
    }
    if (message.key !== undefined && message.key !== "") {
      writer.uint32(18).string(message.key);
    }
    if (message.fileId !== undefined && message.fileId !== "") {
      writer.uint32(26).string(message.fileId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetUploadUrlResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetUploadUrlResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.uploadUrl = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.fileId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetUploadUrlResponse {
    return {
      uploadUrl: isSet(object.uploadUrl)
        ? globalThis.String(object.uploadUrl)
        : isSet(object.upload_url)
        ? globalThis.String(object.upload_url)
        : "",
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      fileId: isSet(object.fileId)
        ? globalThis.String(object.fileId)
        : isSet(object.file_id)
        ? globalThis.String(object.file_id)
        : "",
    };
  },

  toJSON(message: GetUploadUrlResponse): unknown {
    const obj: any = {};
    if (message.uploadUrl !== undefined && message.uploadUrl !== "") {
      obj.uploadUrl = message.uploadUrl;
    }
    if (message.key !== undefined && message.key !== "") {
      obj.key = message.key;
    }
    if (message.fileId !== undefined && message.fileId !== "") {
      obj.fileId = message.fileId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetUploadUrlResponse>, I>>(base?: I): GetUploadUrlResponse {
    return GetUploadUrlResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetUploadUrlResponse>, I>>(object: I): GetUploadUrlResponse {
    const message = createBaseGetUploadUrlResponse();
    message.uploadUrl = object.uploadUrl ?? "";
    message.key = object.key ?? "";
    message.fileId = object.fileId ?? "";
    return message;
  },
};

function createBaseCreateVideoRequest(): CreateVideoRequest {
  return { title: "", description: undefined, url: "", size: 0, duration: 0, format: undefined };
}

export const CreateVideoRequest: MessageFns<CreateVideoRequest> = {
  encode(message: CreateVideoRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.title !== undefined && message.title !== "") {
      writer.uint32(10).string(message.title);
    }
    if (message.description !== undefined) {
      writer.uint32(18).string(message.description);
    }
    if (message.url !== undefined && message.url !== "") {
      writer.uint32(26).string(message.url);
    }
    if (message.size !== undefined && message.size !== 0) {
      writer.uint32(32).int64(message.size);
    }
    if (message.duration !== undefined && message.duration !== 0) {
      writer.uint32(40).int32(message.duration);
    }
    if (message.format !== undefined) {
      writer.uint32(50).string(message.format);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateVideoRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateVideoRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.url = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.size = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.duration = reader.int32();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.format = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateVideoRequest {
    return {
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : undefined,
      url: isSet(object.url) ? globalThis.String(object.url) : "",
      size: isSet(object.size) ? globalThis.Number(object.size) : 0,
      duration: isSet(object.duration) ? globalThis.Number(object.duration) : 0,
      format: isSet(object.format) ? globalThis.String(object.format) : undefined,
    };
  },

  toJSON(message: CreateVideoRequest): unknown {
    const obj: any = {};
    if (message.title !== undefined && message.title !== "") {
      obj.title = message.title;
    }
    if (message.description !== undefined) {
      obj.description = message.description;
    }
    if (message.url !== undefined && message.url !== "") {
      obj.url = message.url;
    }
    if (message.size !== undefined && message.size !== 0) {
      obj.size = Math.round(message.size);
    }
    if (message.duration !== undefined && message.duration !== 0) {
      obj.duration = Math.round(message.duration);
    }
    if (message.format !== undefined) {
      obj.format = message.format;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateVideoRequest>, I>>(base?: I): CreateVideoRequest {
    return CreateVideoRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateVideoRequest>, I>>(object: I): CreateVideoRequest {
    const message = createBaseCreateVideoRequest();
    message.title = object.title ?? "";
    message.description = object.description ?? undefined;
    message.url = object.url ?? "";
    message.size = object.size ?? 0;
    message.duration = object.duration ?? 0;
    message.format = object.format ?? undefined;
    return message;
  },
};

function createBaseCreateVideoResponse(): CreateVideoResponse {
  return { video: undefined };
}

export const CreateVideoResponse: MessageFns<CreateVideoResponse> = {
  encode(message: CreateVideoResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.video !== undefined) {
      Video.encode(message.video, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateVideoResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateVideoResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.video = Video.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateVideoResponse {
    return { video: isSet(object.video) ? Video.fromJSON(object.video) : undefined };
  },

  toJSON(message: CreateVideoResponse): unknown {
    const obj: any = {};
    if (message.video !== undefined) {
      obj.video = Video.toJSON(message.video);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateVideoResponse>, I>>(base?: I): CreateVideoResponse {
    return CreateVideoResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateVideoResponse>, I>>(object: I): CreateVideoResponse {
    const message = createBaseCreateVideoResponse();
    message.video = (object.video !== undefined && object.video !== null) ? Video.fromPartial(object.video) : undefined;
    return message;
  },
};

function createBaseListVideosRequest(): ListVideosRequest {
  return { page: 0, limit: 0, search: undefined, status: undefined };
}

export const ListVideosRequest: MessageFns<ListVideosRequest> = {
  encode(message: ListVideosRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.page !== undefined && message.page !== 0) {
      writer.uint32(8).int32(message.page);
    }
    if (message.limit !== undefined && message.limit !== 0) {
      writer.uint32(16).int32(message.limit);
    }
    if (message.search !== undefined) {
      writer.uint32(26).string(message.search);
    }
    if (message.status !== undefined) {
      writer.uint32(34).string(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListVideosRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListVideosRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.page = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.search = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.status = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListVideosRequest {
    return {
      page: isSet(object.page) ? globalThis.Number(object.page) : 0,
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
      search: isSet(object.search) ? globalThis.String(object.search) : undefined,
      status: isSet(object.status) ? globalThis.String(object.status) : undefined,
    };
  },

  toJSON(message: ListVideosRequest): unknown {
    const obj: any = {};
    if (message.page !== undefined && message.page !== 0) {
      obj.page = Math.round(message.page);
    }
    if (message.limit !== undefined && message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    if (message.search !== undefined) {
      obj.search = message.search;
    }
    if (message.status !== undefined) {
      obj.status = message.status;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListVideosRequest>, I>>(base?: I): ListVideosRequest {
    return ListVideosRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListVideosRequest>, I>>(object: I): ListVideosRequest {
    const message = createBaseListVideosRequest();
    message.page = object.page ?? 0;
    message.limit = object.limit ?? 0;
    message.search = object.search ?? undefined;
    message.status = object.status ?? undefined;
    return message;
  },
};

function createBaseListVideosResponse(): ListVideosResponse {
  return { videos: [], total: 0, page: 0, limit: 0 };
}

export const ListVideosResponse: MessageFns<ListVideosResponse> = {
  encode(message: ListVideosResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.videos !== undefined && message.videos.length !== 0) {
      for (const v of message.videos) {
        Video.encode(v!, writer.uint32(10).fork()).join();
      }
    }
    if (message.total !== undefined && message.total !== 0) {
      writer.uint32(16).int64(message.total);
    }
    if (message.page !== undefined && message.page !== 0) {
      writer.uint32(24).int32(message.page);
    }
    if (message.limit !== undefined && message.limit !== 0) {
      writer.uint32(32).int32(message.limit);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListVideosResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListVideosResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          const el = Video.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.videos!.push(el);
          }
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.total = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.page = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.limit = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListVideosResponse {
    return {
      videos: globalThis.Array.isArray(object?.videos) ? object.videos.map((e: any) => Video.fromJSON(e)) : [],
      total: isSet(object.total) ? globalThis.Number(object.total) : 0,
      page: isSet(object.page) ? globalThis.Number(object.page) : 0,
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
    };
  },

  toJSON(message: ListVideosResponse): unknown {
    const obj: any = {};
    if (message.videos?.length) {
      obj.videos = message.videos.map((e) => Video.toJSON(e));
    }
    if (message.total !== undefined && message.total !== 0) {
      obj.total = Math.round(message.total);
    }
    if (message.page !== undefined && message.page !== 0) {
      obj.page = Math.round(message.page);
    }
    if (message.limit !== undefined && message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListVideosResponse>, I>>(base?: I): ListVideosResponse {
    return ListVideosResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListVideosResponse>, I>>(object: I): ListVideosResponse {
    const message = createBaseListVideosResponse();
    message.videos = object.videos?.map((e) => Video.fromPartial(e)) || [];
    message.total = object.total ?? 0;
    message.page = object.page ?? 0;
    message.limit = object.limit ?? 0;
    return message;
  },
};

function createBaseGetVideoRequest(): GetVideoRequest {
  return { id: "" };
}

export const GetVideoRequest: MessageFns<GetVideoRequest> = {
  encode(message: GetVideoRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined && message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetVideoRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetVideoRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetVideoRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: GetVideoRequest): unknown {
    const obj: any = {};
    if (message.id !== undefined && message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetVideoRequest>, I>>(base?: I): GetVideoRequest {
    return GetVideoRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetVideoRequest>, I>>(object: I): GetVideoRequest {
    const message = createBaseGetVideoRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseGetVideoResponse(): GetVideoResponse {
  return { video: undefined };
}

export const GetVideoResponse: MessageFns<GetVideoResponse> = {
  encode(message: GetVideoResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.video !== undefined) {
      Video.encode(message.video, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetVideoResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetVideoResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.video = Video.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetVideoResponse {
    return { video: isSet(object.video) ? Video.fromJSON(object.video) : undefined };
  },

  toJSON(message: GetVideoResponse): unknown {
    const obj: any = {};
    if (message.video !== undefined) {
      obj.video = Video.toJSON(message.video);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetVideoResponse>, I>>(base?: I): GetVideoResponse {
    return GetVideoResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetVideoResponse>, I>>(object: I): GetVideoResponse {
    const message = createBaseGetVideoResponse();
    message.video = (object.video !== undefined && object.video !== null) ? Video.fromPartial(object.video) : undefined;
    return message;
  },
};

function createBaseUpdateVideoRequest(): UpdateVideoRequest {
  return {
    id: "",
    title: "",
    description: undefined,
    url: "",
    size: 0,
    duration: 0,
    format: undefined,
    status: undefined,
  };
}

export const UpdateVideoRequest: MessageFns<UpdateVideoRequest> = {
  encode(message: UpdateVideoRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined && message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.title !== undefined && message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    if (message.description !== undefined) {
      writer.uint32(26).string(message.description);
    }
    if (message.url !== undefined && message.url !== "") {
      writer.uint32(34).string(message.url);
    }
    if (message.size !== undefined && message.size !== 0) {
      writer.uint32(40).int64(message.size);
    }
    if (message.duration !== undefined && message.duration !== 0) {
      writer.uint32(48).int32(message.duration);
    }
    if (message.format !== undefined) {
      writer.uint32(58).string(message.format);
    }
    if (message.status !== undefined) {
      writer.uint32(66).string(message.status);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateVideoRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateVideoRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.url = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.size = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.duration = reader.int32();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.format = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.status = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateVideoRequest {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : undefined,
      url: isSet(object.url) ? globalThis.String(object.url) : "",
      size: isSet(object.size) ? globalThis.Number(object.size) : 0,
      duration: isSet(object.duration) ? globalThis.Number(object.duration) : 0,
      format: isSet(object.format) ? globalThis.String(object.format) : undefined,
      status: isSet(object.status) ? globalThis.String(object.status) : undefined,
    };
  },

  toJSON(message: UpdateVideoRequest): unknown {
    const obj: any = {};
    if (message.id !== undefined && message.id !== "") {
      obj.id = message.id;
    }
    if (message.title !== undefined && message.title !== "") {
      obj.title = message.title;
    }
    if (message.description !== undefined) {
      obj.description = message.description;
    }
    if (message.url !== undefined && message.url !== "") {
      obj.url = message.url;
    }
    if (message.size !== undefined && message.size !== 0) {
      obj.size = Math.round(message.size);
    }
    if (message.duration !== undefined && message.duration !== 0) {
      obj.duration = Math.round(message.duration);
    }
    if (message.format !== undefined) {
      obj.format = message.format;
    }
    if (message.status !== undefined) {
      obj.status = message.status;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateVideoRequest>, I>>(base?: I): UpdateVideoRequest {
    return UpdateVideoRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateVideoRequest>, I>>(object: I): UpdateVideoRequest {
    const message = createBaseUpdateVideoRequest();
    message.id = object.id ?? "";
    message.title = object.title ?? "";
    message.description = object.description ?? undefined;
    message.url = object.url ?? "";
    message.size = object.size ?? 0;
    message.duration = object.duration ?? 0;
    message.format = object.format ?? undefined;
    message.status = object.status ?? undefined;
    return message;
  },
};

function createBaseUpdateVideoResponse(): UpdateVideoResponse {
  return { video: undefined };
}

export const UpdateVideoResponse: MessageFns<UpdateVideoResponse> = {
  encode(message: UpdateVideoResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.video !== undefined) {
      Video.encode(message.video, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateVideoResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateVideoResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.video = Video.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateVideoResponse {
    return { video: isSet(object.video) ? Video.fromJSON(object.video) : undefined };
  },

  toJSON(message: UpdateVideoResponse): unknown {
    const obj: any = {};
    if (message.video !== undefined) {
      obj.video = Video.toJSON(message.video);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateVideoResponse>, I>>(base?: I): UpdateVideoResponse {
    return UpdateVideoResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateVideoResponse>, I>>(object: I): UpdateVideoResponse {
    const message = createBaseUpdateVideoResponse();
    message.video = (object.video !== undefined && object.video !== null) ? Video.fromPartial(object.video) : undefined;
    return message;
  },
};

function createBaseDeleteVideoRequest(): DeleteVideoRequest {
  return { id: "" };
}

export const DeleteVideoRequest: MessageFns<DeleteVideoRequest> = {
  encode(message: DeleteVideoRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== undefined && message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteVideoRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteVideoRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteVideoRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: DeleteVideoRequest): unknown {
    const obj: any = {};
    if (message.id !== undefined && message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeleteVideoRequest>, I>>(base?: I): DeleteVideoRequest {
    return DeleteVideoRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeleteVideoRequest>, I>>(object: I): DeleteVideoRequest {
    const message = createBaseDeleteVideoRequest();
    message.id = object.id ?? "";
    return message;
  },
};

export type VideosService = typeof VideosService;
export const VideosService = {
  getUploadUrl: {
    path: "/stream.app.v1.Videos/GetUploadUrl",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetUploadUrlRequest): Buffer => Buffer.from(GetUploadUrlRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetUploadUrlRequest => GetUploadUrlRequest.decode(value),
    responseSerialize: (value: GetUploadUrlResponse): Buffer =>
      Buffer.from(GetUploadUrlResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetUploadUrlResponse => GetUploadUrlResponse.decode(value),
  },
  createVideo: {
    path: "/stream.app.v1.Videos/CreateVideo",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CreateVideoRequest): Buffer => Buffer.from(CreateVideoRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): CreateVideoRequest => CreateVideoRequest.decode(value),
    responseSerialize: (value: CreateVideoResponse): Buffer => Buffer.from(CreateVideoResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): CreateVideoResponse => CreateVideoResponse.decode(value),
  },
  listVideos: {
    path: "/stream.app.v1.Videos/ListVideos",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ListVideosRequest): Buffer => Buffer.from(ListVideosRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ListVideosRequest => ListVideosRequest.decode(value),
    responseSerialize: (value: ListVideosResponse): Buffer => Buffer.from(ListVideosResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ListVideosResponse => ListVideosResponse.decode(value),
  },
  getVideo: {
    path: "/stream.app.v1.Videos/GetVideo",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetVideoRequest): Buffer => Buffer.from(GetVideoRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetVideoRequest => GetVideoRequest.decode(value),
    responseSerialize: (value: GetVideoResponse): Buffer => Buffer.from(GetVideoResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetVideoResponse => GetVideoResponse.decode(value),
  },
  updateVideo: {
    path: "/stream.app.v1.Videos/UpdateVideo",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UpdateVideoRequest): Buffer => Buffer.from(UpdateVideoRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): UpdateVideoRequest => UpdateVideoRequest.decode(value),
    responseSerialize: (value: UpdateVideoResponse): Buffer => Buffer.from(UpdateVideoResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): UpdateVideoResponse => UpdateVideoResponse.decode(value),
  },
  deleteVideo: {
    path: "/stream.app.v1.Videos/DeleteVideo",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: DeleteVideoRequest): Buffer => Buffer.from(DeleteVideoRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): DeleteVideoRequest => DeleteVideoRequest.decode(value),
    responseSerialize: (value: MessageResponse): Buffer => Buffer.from(MessageResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): MessageResponse => MessageResponse.decode(value),
  },
} as const;

export interface VideosServer extends UntypedServiceImplementation {
  getUploadUrl: handleUnaryCall<GetUploadUrlRequest, GetUploadUrlResponse>;
  createVideo: handleUnaryCall<CreateVideoRequest, CreateVideoResponse>;
  listVideos: handleUnaryCall<ListVideosRequest, ListVideosResponse>;
  getVideo: handleUnaryCall<GetVideoRequest, GetVideoResponse>;
  updateVideo: handleUnaryCall<UpdateVideoRequest, UpdateVideoResponse>;
  deleteVideo: handleUnaryCall<DeleteVideoRequest, MessageResponse>;
}

export interface VideosClient extends Client {
  getUploadUrl(
    request: GetUploadUrlRequest,
    callback: (error: ServiceError | null, response: GetUploadUrlResponse) => void,
  ): ClientUnaryCall;
  getUploadUrl(
    request: GetUploadUrlRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetUploadUrlResponse) => void,
  ): ClientUnaryCall;
  getUploadUrl(
    request: GetUploadUrlRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetUploadUrlResponse) => void,
  ): ClientUnaryCall;
  createVideo(
    request: CreateVideoRequest,
    callback: (error: ServiceError | null, response: CreateVideoResponse) => void,
  ): ClientUnaryCall;
  createVideo(
    request: CreateVideoRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: CreateVideoResponse) => void,
  ): ClientUnaryCall;
  createVideo(
    request: CreateVideoRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: CreateVideoResponse) => void,
  ): ClientUnaryCall;
  listVideos(
    request: ListVideosRequest,
    callback: (error: ServiceError | null, response: ListVideosResponse) => void,
  ): ClientUnaryCall;
  listVideos(
    request: ListVideosRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ListVideosResponse) => void,
  ): ClientUnaryCall;
  listVideos(
    request: ListVideosRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ListVideosResponse) => void,
  ): ClientUnaryCall;
  getVideo(
    request: GetVideoRequest,
    callback: (error: ServiceError | null, response: GetVideoResponse) => void,
  ): ClientUnaryCall;
  getVideo(
    request: GetVideoRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetVideoResponse) => void,
  ): ClientUnaryCall;
  getVideo(
    request: GetVideoRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetVideoResponse) => void,
  ): ClientUnaryCall;
  updateVideo(
    request: UpdateVideoRequest,
    callback: (error: ServiceError | null, response: UpdateVideoResponse) => void,
  ): ClientUnaryCall;
  updateVideo(
    request: UpdateVideoRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: UpdateVideoResponse) => void,
  ): ClientUnaryCall;
  updateVideo(
    request: UpdateVideoRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: UpdateVideoResponse) => void,
  ): ClientUnaryCall;
  deleteVideo(
    request: DeleteVideoRequest,
    callback: (error: ServiceError | null, response: MessageResponse) => void,
  ): ClientUnaryCall;
  deleteVideo(
    request: DeleteVideoRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: MessageResponse) => void,
  ): ClientUnaryCall;
  deleteVideo(
    request: DeleteVideoRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: MessageResponse) => void,
  ): ClientUnaryCall;
}

export const VideosClient = makeGenericClientConstructor(VideosService, "stream.app.v1.Videos") as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): VideosClient;
  service: typeof VideosService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
