// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.4
//   protoc               unknown
// source: app/v1/video_metadata.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { AdTemplate, Domain, PlayerConfig, PopupAd, Video } from "./common";

export const protobufPackage = "stream.app.v1";

export interface GetVideoMetadataRequest {
  videoId?: string | undefined;
}

export interface GetVideoMetadataResponse {
  video?: Video | undefined;
  defaultPlayerConfig?: PlayerConfig | undefined;
  adTemplate?: AdTemplate | undefined;
  activePopupAd?: PopupAd | undefined;
  domains?: Domain[] | undefined;
}

function createBaseGetVideoMetadataRequest(): GetVideoMetadataRequest {
  return { videoId: "" };
}

export const GetVideoMetadataRequest: MessageFns<GetVideoMetadataRequest> = {
  encode(message: GetVideoMetadataRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.videoId !== undefined && message.videoId !== "") {
      writer.uint32(10).string(message.videoId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetVideoMetadataRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetVideoMetadataRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.videoId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetVideoMetadataRequest {
    return {
      videoId: isSet(object.videoId)
        ? globalThis.String(object.videoId)
        : isSet(object.video_id)
        ? globalThis.String(object.video_id)
        : "",
    };
  },

  toJSON(message: GetVideoMetadataRequest): unknown {
    const obj: any = {};
    if (message.videoId !== undefined && message.videoId !== "") {
      obj.videoId = message.videoId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetVideoMetadataRequest>, I>>(base?: I): GetVideoMetadataRequest {
    return GetVideoMetadataRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetVideoMetadataRequest>, I>>(object: I): GetVideoMetadataRequest {
    const message = createBaseGetVideoMetadataRequest();
    message.videoId = object.videoId ?? "";
    return message;
  },
};

function createBaseGetVideoMetadataResponse(): GetVideoMetadataResponse {
  return {
    video: undefined,
    defaultPlayerConfig: undefined,
    adTemplate: undefined,
    activePopupAd: undefined,
    domains: [],
  };
}

export const GetVideoMetadataResponse: MessageFns<GetVideoMetadataResponse> = {
  encode(message: GetVideoMetadataResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.video !== undefined) {
      Video.encode(message.video, writer.uint32(10).fork()).join();
    }
    if (message.defaultPlayerConfig !== undefined) {
      PlayerConfig.encode(message.defaultPlayerConfig, writer.uint32(18).fork()).join();
    }
    if (message.adTemplate !== undefined) {
      AdTemplate.encode(message.adTemplate, writer.uint32(26).fork()).join();
    }
    if (message.activePopupAd !== undefined) {
      PopupAd.encode(message.activePopupAd, writer.uint32(34).fork()).join();
    }
    if (message.domains !== undefined && message.domains.length !== 0) {
      for (const v of message.domains) {
        Domain.encode(v!, writer.uint32(42).fork()).join();
      }
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetVideoMetadataResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetVideoMetadataResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.video = Video.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.defaultPlayerConfig = PlayerConfig.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.adTemplate = AdTemplate.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.activePopupAd = PopupAd.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          const el = Domain.decode(reader, reader.uint32());
          if (el !== undefined) {
            message.domains!.push(el);
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetVideoMetadataResponse {
    return {
      video: isSet(object.video) ? Video.fromJSON(object.video) : undefined,
      defaultPlayerConfig: isSet(object.defaultPlayerConfig)
        ? PlayerConfig.fromJSON(object.defaultPlayerConfig)
        : isSet(object.default_player_config)
        ? PlayerConfig.fromJSON(object.default_player_config)
        : undefined,
      adTemplate: isSet(object.adTemplate)
        ? AdTemplate.fromJSON(object.adTemplate)
        : isSet(object.ad_template)
        ? AdTemplate.fromJSON(object.ad_template)
        : undefined,
      activePopupAd: isSet(object.activePopupAd)
        ? PopupAd.fromJSON(object.activePopupAd)
        : isSet(object.active_popup_ad)
        ? PopupAd.fromJSON(object.active_popup_ad)
        : undefined,
      domains: globalThis.Array.isArray(object?.domains) ? object.domains.map((e: any) => Domain.fromJSON(e)) : [],
    };
  },

  toJSON(message: GetVideoMetadataResponse): unknown {
    const obj: any = {};
    if (message.video !== undefined) {
      obj.video = Video.toJSON(message.video);
    }
    if (message.defaultPlayerConfig !== undefined) {
      obj.defaultPlayerConfig = PlayerConfig.toJSON(message.defaultPlayerConfig);
    }
    if (message.adTemplate !== undefined) {
      obj.adTemplate = AdTemplate.toJSON(message.adTemplate);
    }
    if (message.activePopupAd !== undefined) {
      obj.activePopupAd = PopupAd.toJSON(message.activePopupAd);
    }
    if (message.domains?.length) {
      obj.domains = message.domains.map((e) => Domain.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetVideoMetadataResponse>, I>>(base?: I): GetVideoMetadataResponse {
    return GetVideoMetadataResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetVideoMetadataResponse>, I>>(object: I): GetVideoMetadataResponse {
    const message = createBaseGetVideoMetadataResponse();
    message.video = (object.video !== undefined && object.video !== null) ? Video.fromPartial(object.video) : undefined;
    message.defaultPlayerConfig = (object.defaultPlayerConfig !== undefined && object.defaultPlayerConfig !== null)
      ? PlayerConfig.fromPartial(object.defaultPlayerConfig)
      : undefined;
    message.adTemplate = (object.adTemplate !== undefined && object.adTemplate !== null)
      ? AdTemplate.fromPartial(object.adTemplate)
      : undefined;
    message.activePopupAd = (object.activePopupAd !== undefined && object.activePopupAd !== null)
      ? PopupAd.fromPartial(object.activePopupAd)
      : undefined;
    message.domains = object.domains?.map((e) => Domain.fromPartial(e)) || [];
    return message;
  },
};

export type VideoMetadataService = typeof VideoMetadataService;
export const VideoMetadataService = {
  getVideoMetadata: {
    path: "/stream.app.v1.VideoMetadata/GetVideoMetadata",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetVideoMetadataRequest): Buffer =>
      Buffer.from(GetVideoMetadataRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetVideoMetadataRequest => GetVideoMetadataRequest.decode(value),
    responseSerialize: (value: GetVideoMetadataResponse): Buffer =>
      Buffer.from(GetVideoMetadataResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetVideoMetadataResponse => GetVideoMetadataResponse.decode(value),
  },
} as const;

export interface VideoMetadataServer extends UntypedServiceImplementation {
  getVideoMetadata: handleUnaryCall<GetVideoMetadataRequest, GetVideoMetadataResponse>;
}

export interface VideoMetadataClient extends Client {
  getVideoMetadata(
    request: GetVideoMetadataRequest,
    callback: (error: ServiceError | null, response: GetVideoMetadataResponse) => void,
  ): ClientUnaryCall;
  getVideoMetadata(
    request: GetVideoMetadataRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetVideoMetadataResponse) => void,
  ): ClientUnaryCall;
  getVideoMetadata(
    request: GetVideoMetadataRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetVideoMetadataResponse) => void,
  ): ClientUnaryCall;
}

export const VideoMetadataClient = makeGenericClientConstructor(
  VideoMetadataService,
  "stream.app.v1.VideoMetadata",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): VideoMetadataClient;
  service: typeof VideoMetadataService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
